/**
 * quizDataNew.js — Nouvelles matières NS4
 * Source : Programmes officiels MENFP, version définitive 24 juillet 2024
 *
 * INTÉGRATION :
 * 1. Renommer quizData.js → quizDataBase.js
 * 2. Placer ce fichier dans le même dossier que quizDataBase.js
 * 3. Remplacer quizData.js par le fichier merger (quizData.js fourni séparément)
 */

export const QUIZ_DATA_NEW = {

  // ============================================================
  // SVT → GÉOLOGIE
  // ============================================================
  "Géologie": [
    { q: "Les roches magmatiques se forment par :", choices: ["L'accumulation de sédiments compactés", "La solidification du magma (refroidissement de la lave ou du magma en profondeur)", "La transformation de roches sous haute pression", "L'érosion et le dépôt de particules"], answer: 1, note: "Roches ignées : intrusives (granite — refroidissement lent, grands cristaux) ou extrusives (basalte — refroidissement rapide, petits cristaux)." },
    { q: "Le granite est une roche magmatique :", choices: ["Extrusive (lave refroidie en surface)", "Intrusive (magma refroidi lentement en profondeur)", "Sédimentaire calcaire", "Métamorphique"], answer: 1, note: "Granite : intrusive à gros cristaux (quartz, feldspath, mica). Refroidissement lent → grands cristaux visibles à l'œil nu." },
    { q: "Le basalte est une roche magmatique :", choices: ["Intrusive à gros cristaux", "Extrusive (lave refroidie rapidement en surface) — compose le fond des océans", "Sédimentaire organique", "Métamorphique foliée"], answer: 1, note: "Basalte : extrusive à fins cristaux. Refroidissement rapide de la lave. Roche la plus abondante de la lithosphère océanique." },
    { q: "Les roches sédimentaires se forment par :", choices: ["Solidification du magma", "Accumulation, compaction et cimentation de sédiments (débris de roches, organismes)", "Transformation sous haute pression et température", "Cristallisation à haute température"], answer: 1, note: "Roches sédimentaires : calcaire, grès, argile. Formées en couches (strates) dans l'eau ou à l'air. Contiennent souvent des fossiles." },
    { q: "Le calcaire est une roche sédimentaire :", choices: ["Détritique (fragments de roches)", "Biochimique (accumulation de coquilles calcaires d'organismes marins)", "Magmatique extrusive", "Métamorphique"], answer: 1, note: "Calcaire (CaCO₃) : biochimique, issu de squelettes d'organismes marins. Très répandu en Haïti — utilisé dans la construction et cimenterie." },
    { q: "Les roches métamorphiques résultent de :", choices: ["L'érosion de roches existantes", "La transformation de roches préexistantes à l'état solide sous haute pression et/ou température", "La solidification du magma en profondeur", "L'accumulation de sédiments organiques"], answer: 1, note: "Métamorphisme : transformation sans fusion. Calcaire → marbre, granite → gneiss, argile → schiste." },
    { q: "Le marbre est une roche métamorphique issue de :", choices: ["L'argile sous haute pression", "La transformation du calcaire sous haute pression et température", "La solidification du magma", "L'accumulation de sédiments marins"], answer: 1, note: "Marbre = métamorphisme du calcaire (CaCO₃). Haïti possède des gisements de marbre (pierre marbrière) — ressource valorisable." },
    { q: "Les deux grands types de volcans sont :", choices: ["Actifs et éteints", "Effusifs (lave fluide, peu explosifs) et explosifs (lave visqueuse, très dangereux)", "Marins et terrestres uniquement", "Jeunes et anciens"], answer: 1, note: "Effusifs (Hawaii, Piton de la Fournaise) : lave basaltique fluide → coulées. Explosifs (Soufrière, Pelée) : lave acide et visqueuse → explosions violentes, nuées ardentes." },
    { q: "Un séisme est causé par :", choices: ["L'éruption volcanique uniquement", "La rupture soudaine de roches sous contrainte tectonique le long d'une faille, libérant de l'énergie (ondes sismiques)", "L'érosion des côtes", "Le mouvement des océans"], answer: 1, note: "Séisme : rupture en profondeur (foyer/hypocentre) → ondes sismiques → secousses en surface (épicentre)." },
    { q: "L'échelle de Richter mesure :", choices: ["L'intensité ressentie par la population", "La magnitude (énergie libérée) d'un séisme — échelle logarithmique", "La durée d'un séisme", "La profondeur du foyer"], answer: 1, note: "Magnitude (Richter) : chaque point = 32× plus d'énergie. Séisme haïtien du 12/01/2010 = magnitude 7,0 → catastrophe majeure." },
    { q: "Haïti est particulièrement exposée aux séismes car :", choices: ["Le sol haïtien est très mou", "Elle est à la frontière des plaques caribéenne et nord-américaine — faille Enriquillo active", "Les volcans créent des séismes constants", "L'érosion fragilise les sols"], answer: 1, note: "Faille Enriquillo-Plantain Garden (transformante) : frontière Caraïbe/Amérique du Nord traverse Haïti → forte sismicité. Séisme 12/01/2010 : ~220 000 morts." },
    { q: "La stratigraphie est la science qui étudie :", choices: ["La structure chimique des roches", "Les couches (strates) géologiques et leur succession chronologique", "Les minéraux uniquement", "Les fossiles exclusivement"], answer: 1, note: "Stratigraphie : étude des strates pour reconstituer l'histoire géologique. Permet de dater les formations et corréler des sites éloignés." },
    { q: "Le principe de superposition (Sténon, 1669) dit que :", choices: ["Les couches les plus récentes sont en bas", "Dans une série non perturbée, les couches les plus anciennes sont en bas, les plus récentes en haut", "Toutes les couches ont le même âge", "La couche la plus épaisse est la plus ancienne"], answer: 1, note: "Principe fondamental de stratigraphie. Base de la datation relative des strates géologiques." },
    { q: "Un fossile stratigraphique (fossile guide) se caractérise par :", choices: ["Une longue durée d'existence et distribution limitée", "Une courte durée d'existence géologique et une large distribution — permet de dater les strates", "Un habitat uniquement aquatique", "Une grande taille"], answer: 1, note: "Fossile guide : espèce éteinte à existence brève (~1 Ma) et distribution mondiale → outil de datation relative des strates. Ex: Ammonites (Mésozoïque)." },
    { q: "La paléontologie est :", choices: ["L'étude des roches uniquement", "La science des êtres vivants du passé à travers l'étude des fossiles — histoire de la vie sur Terre", "L'étude des minéraux", "L'étude des séismes"], answer: 1, note: "Paléontologie : fossiles → morphologie, comportement, environnement des organismes anciens → reconstitution de l'histoire de la vie." },
    { q: "La pédologie est la science qui étudie :", choices: ["Les roches magmatiques", "Les sols — leur formation (pédogenèse), composition, types et propriétés", "Les fossiles", "Les eaux souterraines"], answer: 1, note: "Pédologie : formation du sol par altération de la roche mère + matière organique. Horizons A (humus), B (minéraux), C (roche altérée)." },
    { q: "L'érosion des sols en Haïti est aggravée principalement par :", choices: ["L'excès de pluie uniquement", "La déforestation massive (~98% déboisée) qui prive le sol de sa couverture végétale protectrice", "Les séismes exclusivement", "Le surpâturage uniquement"], answer: 1, note: "Érosion haïtienne : déforestation → sol nu → pluies tropicales intenses → érosion hydrique → désertification. Haïti perd ~36 millions de tonnes de sol/an." },
    { q: "Une nappe phréatique est :", choices: ["Un lac en surface", "Une accumulation d'eau souterraine dans les roches perméables (aquifère) — réservoir d'eau souterrain", "Un fleuve souterrain visible", "Un lac artificiel"], answer: 1, note: "Nappe phréatique : eau infiltrée stockée dans les pores/fissures des roches perméables. Source essentielle d'eau potable en Haïti (zones rurales)." },
    { q: "Les minerais métalliques présents en Haïti comprennent :", choices: ["Uniquement du pétrole", "Du cuivre et de l'or (nord, région Morne Bossa) et de la bauxite (historiquement — Miragoane)", "Uniquement du charbon", "Du fer et de l'aluminium uniquement"], answer: 1, note: "Haïti : gisements d'or et cuivre (nord, Morne Bossa — exploré par Newmont), bauxite (Miragoane — exploitée jusqu'aux années 1980). Sous-exploités. Programme MENFP." },
    { q: "Les minerais non métalliques présents en Haïti incluent :", choices: ["Le diamant et le rubis", "Le calcaire (marbre), l'argile, le sel gemme, le lignite", "L'uranium et le titane", "Le platine et le lithium"], answer: 1, note: "Haïti : calcaire abondant (construction/ciment), marbre, argile, sel gemme, lignite. Programme MENFP : géologie économique haïtienne." },
    { q: "La crise Crétacé-Tertiaire (K-Pg, ~66 Ma) est marquée par :", choices: ["L'apparition des dinosaures", "La disparition massive de ~75% des espèces dont les dinosaures non-aviaires — impact météoritique + volcanisme", "L'émergence des mammifères uniquement", "Une glaciation majeure"], answer: 1, note: "Crise K-Pg : impact de Chicxulub (Mexique) + trapps du Deccan → disparition de 75% des espèces. Fin des dinosaures, début de l'ère des mammifères." },
    { q: "La géomorphologie étudie :", choices: ["La composition chimique des roches", "Les formes du relief terrestre (montagnes, vallées, côtes) et les processus qui les créent", "Les minéraux uniquement", "Les volcans exclusivement"], answer: 1, note: "Géomorphologie : érosion, dépôt, tectonique → formes du relief. Haïti : relief montagneux (~70%) → fortes contraintes géomorphologiques." },
    { q: "La géomorphologie marine étudie :", choices: ["Les vagues uniquement", "Les formes du relief des fonds marins et des côtes — plateaux continentaux, dorsales, fosses océaniques", "Les tempêtes tropicales", "La pollution marine"], answer: 1, note: "Géomorphologie marine : plateaux continentaux, pentes, fosses (~11 000 m), dorsales médio-océaniques, plaines abyssales. Côtier : falaises, plages, deltas." },
    { q: "L'hydrogéologie étudie :", choices: ["Les océans et les mers", "Les eaux souterraines — présence, mouvement, qualité et exploitation des aquifères", "Les rivières uniquement", "Les glaciers"], answer: 1, note: "Hydrogéologie : eau souterraine dans les aquifères — captage de sources, forages, protection des nappes. Essentielle pour l'alimentation en eau d'Haïti." },
    { q: "La datation radiométrique permet de :", choices: ["Dater les strates par leur position relative", "Calculer l'âge absolu des roches à partir de la désintégration d'isotopes radioactifs (C14, K-Ar, U-Pb)", "Dater les fossiles par morphologie", "Estimer l'âge par la couleur des roches"], answer: 1, note: "Radiométrie : C14 (<50 000 ans), K-Ar et U-Pb (roches anciennes, milliards d'années). Donne des âges absolus en millions d'années." },
    { q: "L'hominisation désigne :", choices: ["La domestication des animaux", "Le processus évolutif conduisant de nos ancêtres primates à Homo sapiens — sur ~7 millions d'années", "L'émergence des dinosaures", "La colonisation de nouveaux continents uniquement"], answer: 1, note: "Hominisation : Australopithèques → Homo habilis → Homo erectus → Homo sapiens. Émergence en Afrique subsaharienne." },
    { q: "La tectonique des plaques explique :", choices: ["Uniquement les tremblements de terre", "Les volcans, séismes, formation des montagnes, dérive des continents — mouvements des plaques lithosphériques", "Uniquement la formation des océans", "La météorologie"], answer: 1, note: "Tectonique des plaques : la lithosphère divisée en plaques rigides sur l'asthénosphère. Frontières = zones de volcans, séismes, orogénèse (formation des montagnes)." },
    { q: "Les changements climatiques actuels affectent la géologie haïtienne en :", choices: ["Stabilisant les pentes", "Intensifiant les précipitations extrêmes → érosion accélérée, glissements de terrain et inondations plus fréquents", "Réduisant l'érosion côtière", "Favorisant la formation de nouveaux sols fertiles"], answer: 1, note: "Changements climatiques + déforestation haïtienne → précipitations intenses + sol nu → érosion catastrophique. Haïti : pays parmi les plus vulnérables au monde." },
  ],

  // ============================================================
  // SES → HISTOIRE
  // ============================================================
  "Histoire": [
    { q: "Les premiers habitants d'Haïti (avant Colomb) étaient les :", choices: ["Aztèques", "Taïno (Arawak) — peuple amérindien qui appelait l'île 'Ayiti' (terre des montagnes)", "Mayas", "Caraïbes exclusivement"], answer: 1, note: "Taïno : peuple autochtone. Présents depuis ~5000 av. J.-C. Décimés par la colonisation espagnole (maladies, esclavage, violence)." },
    { q: "Christophe Colomb a débarqué sur Hispaniola en :", choices: ["1402", "1492 (5 décembre) — lors de son premier voyage", "1500", "1510"], answer: 1, note: "Colomb débarque le 5 décembre 1492. Fort La Navidad : premier établissement européen dans les Amériques." },
    { q: "Saint-Domingue était surnommée :", choices: ["La pauvre colonie", "'La perle des Antilles' — la colonie française la plus riche du monde au 18e siècle", "L'île des esclaves", "Le paradis tropical"], answer: 1, note: "Saint-Domingue : 1/3 occidental d'Hispaniola. Au 18e siècle, produisait 40% du sucre et 50% du café mondiaux — basée sur l'esclavage de ~500 000 personnes." },
    { q: "La cérémonie du Bois Caïman eut lieu le :", choices: ["1er janvier 1804", "14 août 1791 — déclencheur symbolique de la Révolution haïtienne", "18 novembre 1803", "22 août 1791"], answer: 1, note: "Bois Caïman : nuit du 14 août 1791. Cérémonie vodou avec Dutty Boukman → début de l'insurrection générale des esclaves de Saint-Domingue." },
    { q: "Toussaint Louverture est connu pour :", choices: ["Avoir proclamé l'indépendance d'Haïti", "Avoir dirigé la Révolution haïtienne et proclamé la Constitution de 1801 — 'Napoléon Noir'", "Avoir vaincu les Français à Vertières", "Avoir fondé la République d'Haïti"], answer: 1, note: "Toussaint Louverture (1743-1803) : ex-esclave devenu général, unifie l'île, Constitution de 1801. Arrêté par Napoléon, mort au Fort de Joux en France." },
    { q: "Jean-Jacques Dessalines a proclamé l'indépendance d'Haïti le :", choices: ["14 août 1791", "18 novembre 1803", "1er janvier 1804 à Gonaïves", "22 janvier 1804"], answer: 2, note: "Indépendance : 1er janvier 1804 à Gonaïves. Jean-Jacques Dessalines proclame la première République noire du monde." },
    { q: "La bataille de Vertières (18 novembre 1803) est :", choices: ["Une défaite de l'armée haïtienne", "La victoire décisive de Dessalines et Capois sur l'armée française de Rochambeau — dernière bataille avant l'indépendance", "Une bataille navale", "Un combat contre les Espagnols"], answer: 1, note: "Vertières (Cap-Haïtien, 18/11/1803) : reddition française. 44 jours plus tard : proclamation de l'indépendance." },
    { q: "La dette d'indépendance imposée à Haïti par la France en 1825 était de :", choices: ["10 millions de francs", "150 millions de francs-or — indemnité pour 'compenser' les colons pour leur 'perte'", "50 millions de francs", "500 millions de francs"], answer: 1, note: "Dette coloniale : Charles X impose 150 millions de francs-or sous pression de canons français. Haïti finit de rembourser en 1947 — fardeau économique historique." },
    { q: "Alexandre Pétion (1770-1818) est célèbre pour :", choices: ["Avoir fondé Port-au-Prince", "La réforme agraire (distribution de terres aux anciens esclaves) et l'aide à Simón Bolívar", "Avoir proclamé l'indépendance", "La rédaction de la Constitution de 1801"], answer: 1, note: "Pétion : fondateur de la République (sud). Réforme agraire démocratique. Aide à Bolívar : armes, soldats, argent → indépendance latino-américaine." },
    { q: "Henri Christophe (1767-1820) est connu pour :", choices: ["La réforme agraire dans le sud", "La construction de la Citadelle Laferrière et du Palais Sans-Souci — roi du nord d'Haïti", "La proclamation de l'indépendance", "La rédaction du premier code civil"], answer: 1, note: "Henri Christophe : roi du nord (1811-1820). Citadelle Laferrière (1805-1820) : Patrimoine UNESCO. Palais Sans-Souci : résidence royale." },
    { q: "L'occupation américaine d'Haïti (1915-1934) a été justifiée par les USA par :", choices: ["La demande du gouvernement haïtien", "Des raisons géostratégiques (Canal de Panama, stabilité politique, dettes envers banques américaines)", "Une invasion étrangère d'Haïti", "Une épidémie qui menaçait les USA"], answer: 1, note: "Occupation US (28/07/1915 - 15/08/1934) : 19 ans de présence militaire. Motivations : intérêts bancaires (National City Bank), géostratégie caribéenne." },
    { q: "Charlemagne Péralte (1886-1919) est :", choices: ["Un président haïtien", "Le chef militaire des cacos, résistance armée contre l'occupation américaine — assassiné le 1er novembre 1919", "Un poète national", "Un diplomate haïtien"], answer: 1, note: "Charlemagne Péralte : héros national. Chef des cacos (paysans résistants). Assassiné par des Marines le 1er novembre 1919 — symbole de la résistance haïtienne." },
    { q: "François Duvalier (Papa Doc) a instauré sa dictature à partir de :", choices: ["1934", "1957 (élu président) — se proclame président à vie en 1964", "1971", "1986"], answer: 1, note: "Papa Doc Duvalier : médecin, élu président en 1957. Dictature totalitaire avec les Tontons Macoutes (VSN). Président à vie (1964), mort en 1971." },
    { q: "Les Tontons Macoutes (VSN) étaient :", choices: ["Des soldats réguliers", "La milice paramilitaire de Duvalier — instrument de terreur, répression et assassinats politiques (1959-1986)", "Des résistants contre la dictature", "Des policiers formés par les USA"], answer: 1, note: "Tontons Macoutes (Volontaires de la Sécurité Nationale) : ~9 000 membres, impunité totale. Actes de terreur, exécutions sommaires, intimidation de la population." },
    { q: "Jean-Claude Duvalier (Baby Doc) a quitté le pouvoir le :", choices: ["1er janvier 1971", "7 février 1986 — fuite en France sous pression populaire", "30 septembre 1991", "14 octobre 1994"], answer: 1, note: "Jean-Claude Duvalier : au pouvoir depuis la mort de son père (1971). Renversé par soulèvement populaire ('déchoukaï') le 7 février 1986, fuite en France." },
    { q: "La Première Guerre mondiale (1914-1918) a opposé :", choices: ["La France seule à l'Allemagne", "La Triple Entente (France, Royaume-Uni, Russie) + USA (1917) aux Puissances centrales (Allemagne, Autriche-Hongrie)", "Les USA à l'Allemagne uniquement", "L'Europe entière contre les USA"], answer: 1, note: "1ère GM : ~17 millions de morts. L'assassinat de l'archiduc François-Ferdinand à Sarajevo (28/06/1914) déclenche la crise via le jeu des alliances." },
    { q: "Le traité de Versailles (1919) a imposé à l'Allemagne :", choices: ["Des réparations légères", "Des réparations colossales, la perte de territoires, la limitation militaire et la clause de culpabilité (Art. 231)", "Un traitement équitable", "Une aide à la reconstruction"], answer: 1, note: "Traité de Versailles : 132 milliards de marks-or de réparations, perte de l'Alsace-Lorraine, article 231 (culpabilité de la guerre) → terreau du nazisme." },
    { q: "La Shoah (Holocauste) désigne :", choices: ["Une bataille militaire majeure", "Le génocide systématique de 6 millions de Juifs (et d'autres minorités) par le régime nazi (1941-1945)", "Un bombardement allié", "L'invasion de la Pologne"], answer: 1, note: "Shoah : extermination planifiée (Conférence de Wannsee, janvier 1942). Camps de la mort : Auschwitz, Treblinka, Sobibor... 6 millions de Juifs assassinés." },
    { q: "Le débarquement en Normandie (D-Day, 6 juin 1944) fut :", choices: ["Un débarquement allemand", "L'opération Overlord — débarquement allié en France ouvrant un 2ème front contre l'Allemagne nazie", "Une tentative échouée", "Une opération soviétique"], answer: 1, note: "D-Day (6/06/1944) : Overlord — 156 000 soldats (USA, UK, Canada, France libre) sur 5 plages normandes. Tournant décisif de la guerre en Europe." },
    { q: "La Guerre Froide (1947-1991) était :", choices: ["Un conflit militaire direct entre USA et URSS", "Une rivalité idéologique et stratégique indirecte entre USA (capitalisme) et URSS (communisme)", "Une guerre économique uniquement", "Un conflit uniquement en Europe"], answer: 1, note: "Guerre Froide : course aux armements, conquête spatiale, guerres par procuration (Corée, Vietnam). Fin : dissolution de l'URSS (25/12/1991)." },
    { q: "La chute du mur de Berlin (9 novembre 1989) symbolise :", choices: ["Le début de la Guerre Froide", "La fin de la Guerre Froide et la réunification allemande", "La fin de la 2ème Guerre mondiale", "Le début de la décolonisation"], answer: 1, note: "Mur de Berlin (1961-1989) : symbole de la division Est/Ouest. Sa chute annonce la dissolution de l'URSS (1991) et la fin de la Guerre Froide." },
    { q: "La décolonisation africaine s'est principalement produite :", choices: ["Dans les années 1900-1920", "Dans les années 1950-1960 — 1960 = 'Année de l'Afrique' : 17 pays indépendants", "Dans les années 1970-1980", "Dans les années 1930-1940"], answer: 1, note: "Décolonisation : Ghana (1957, Nkrumah), 1960 (17 pays), Algérie (1962, guerre sanglante), Zimbabwe (1980). Marquée par des guerres d'indépendance et des négociations." },
    { q: "Jean-Bertrand Aristide fut le premier président démocratiquement élu d'Haïti en :", choices: ["1986", "1990 — renversé par coup d'État militaire en 1991", "1994", "2000"], answer: 1, note: "Aristide : élu décembre 1990, renversé 30 septembre 1991 (coup d'État Cédras). Restauré en 1994 (intervention US). Réélu 2000, exilé 2004." },
    { q: "Anténor Firmin (1850-1911) est célèbre pour :", choices: ["La rédaction de la Constitution haïtienne de 1987", "'De l'égalité des races humaines' (1885) — réfutation scientifique du racisme de Gobineau", "La fondation de l'Indigénisme", "La guerre contre l'occupation américaine"], answer: 1, note: "Firmin : intellectuel haïtien, précurseur de la négritude. Réfute 'L'Essai sur l'inégalité des races humaines' de Gobineau par la science." },
    { q: "La MINUSTAH était :", choices: ["Une organisation économique caribéenne", "La Mission des Nations Unies pour la Stabilisation en Haïti (2004-2017)", "Un traité commercial", "Un programme d'aide alimentaire"], answer: 1, note: "MINUSTAH (2004-2017) : force ONU déployée après la crise politique d'Aristide. Controversée : choléra introduit par casques bleus népalais (2010) → 10 000 morts." },
    { q: "La Révolution française (1789) a influencé la Révolution haïtienne car :", choices: ["Elle a directement envoyé des troupes en Haïti", "Les idéaux de liberté, égalité et fraternité ont inspiré les esclaves de Saint-Domingue à réclamer leurs droits", "Elle a aboli l'esclavage en 1789 immédiatement", "Elle a donné l'indépendance directement à Haïti"], answer: 1, note: "Contradiction révolutionnaire : 'liberté-égalité' pour les Blancs, esclavage maintenu pour les Noirs → révolution des esclaves pour appliquer les principes révolutionnaires." },
    { q: "Le séisme du 12 janvier 2010 en Haïti a causé :", choices: ["5 000 morts", "Environ 220 000 à 316 000 morts, 1,5 million de déplacés et destruction massive de Port-au-Prince", "50 000 morts", "1 million de morts"], answer: 1, note: "Séisme 12/01/2010 (M 7,0) : plus grand désastre naturel de l'hémisphère occidental. 1,5M déplacés, dégâts ~7,8 milliards de dollars." },
    { q: "L'ONU a été créée en :", choices: ["1920 (SDN)", "1945 (Charte de San Francisco, 26 juin)", "1948", "1919 (Traité de Versailles)"], answer: 1, note: "ONU : fondée le 26 juin 1945 à San Francisco. 51 membres fondateurs (dont Haïti). Siège à New York. Remplace la SDN (Société des Nations)." },
    { q: "La CARICOM a été fondée en :", choices: ["1958", "1973 (Traité de Chaguaramas, Trinidad) — Haïti y adhère en 2002", "1991", "2000"], answer: 1, note: "CARICOM (1973) : organisation d'intégration caribéenne — libre-échange, coordination politique, CSME (marché unique). 15 États membres + 5 associés." },
    { q: "Marie-Jeanne Lamartinière est connue pour :", choices: ["Sa poésie", "Sa participation armée à la Révolution haïtienne (bataille de Crête-à-Pierrot, 1802)", "Sa philosophie", "Son œuvre littéraire"], answer: 1, note: "Marie-Jeanne Lamartinière (La Pélerine) : figure féminine héroïque de la Révolution haïtienne. Combattante à la bataille de Crête-à-Pierrot (1802)." },
  ],

  // ============================================================
  // SES → GÉOGRAPHIE
  // ============================================================
  "Géographie": [
    { q: "La superficie d'Haïti est d'environ :", choices: ["17 000 km²", "27 750 km² — environ 1/3 de l'île d'Hispaniola", "50 000 km²", "100 000 km²"], answer: 1, note: "Haïti : 27 750 km² (comparable à la Belgique). L'île d'Hispaniola (76 480 km²) est partagée avec la République Dominicaine." },
    { q: "Haïti est divisée en combien de départements ?", choices: ["8", "10 départements administratifs", "12", "15"], answer: 1, note: "10 départements : Ouest, Sud, Grand'Anse, Nippes, Nord, Nord-Ouest, Nord-Est, Artibonite, Centre, Sud-Est. Le département de l'Ouest concentre ~40% de la population." },
    { q: "Le plus long fleuve d'Haïti est :", choices: ["La Rivière du Sud", "L'Artibonite (320 km) — principal fleuve agricole et hydroélectrique", "La Grande Rivière du Nord", "Le Lac Azuéi"], answer: 1, note: "Artibonite : 320 km, prend sa source en RD. Plaine de l'Artibonite = principale zone rizicole ('grenier d'Haïti'). Barrage de Péligre (hydroélectricité)." },
    { q: "Le relief d'Haïti est caractérisé par :", choices: ["Un territoire essentiellement plat", "Un relief montagneux dominant (~70% du territoire) avec des plaines côtières limitées", "Des déserts étendus", "Des forêts tropicales denses sur tout le territoire"], answer: 1, note: "Haïti : ~70% de relief montagneux. Massif du Nord, Massif du Sud, Massif de la Selle (Pic la Selle : 2 674 m — point culminant)." },
    { q: "Le Pic la Selle est :", choices: ["Un volcan actif", "Le point culminant d'Haïti à 2 674 m — dans le Massif de la Selle au sud-est", "Un lac d'altitude", "Un monument historique"], answer: 1, note: "Pic la Selle (2 674 m) : plus haute montagne d'Haïti, département du Sud-Est. Forêts de pins, réserve biologique, zone de captage d'eau." },
    { q: "Le Lac Azuéi (Étang Saumâtre) est :", choices: ["Un lac d'eau douce", "Le plus grand lac d'Haïti — lac saumâtre à la frontière haïtiano-dominicaine", "Un lac artificiel", "Un lac volcanique"], answer: 1, note: "Lac Azuéi (Étang Saumâtre) : 170 km², eau saumâtre. Abrite des crocodiles américains et flamants roses. Plaine du Cul-de-Sac (département Ouest)." },
    { q: "L'île d'Hispaniola est partagée entre :", choices: ["Haïti et Cuba", "Haïti (ouest) et la République Dominicaine (est)", "Haïti et Porto Rico", "Haïti et la Jamaïque"], answer: 1, note: "Hispaniola : 2ème plus grande île des Caraïbes (76 480 km²). Frontière terrestre de 360 km. Contraste saisissant : déforestation côté haïtien vs forêts côté dominicain." },
    { q: "La plaine de l'Artibonite est importante car :", choices: ["C'est la zone touristique principale", "C'est la principale zone rizicole d'Haïti — 'grenier d'Haïti' produisant ~40% du riz national", "C'est la zone industrielle principale", "C'est le centre administratif d'Haïti"], answer: 1, note: "Plaine de l'Artibonite : ~500 km², irriguée par l'Artibonite et le barrage de Péligre. Riz, maïs, haricots, bananes. Zone la plus fertile d'Haïti." },
    { q: "Port-au-Prince est :", choices: ["La deuxième ville d'Haïti", "La capitale et principale ville d'Haïti — ~3-4 millions d'habitants dans l'aire métropolitaine", "Un port commercial sans fonction administrative", "Une ville coloniale espagnole"], answer: 1, note: "Port-au-Prince (fondée 1749, capitale depuis 1770) : ~3-4 millions d'habitants (aire métro), soit ~40% de la population nationale. Département Ouest." },
    { q: "Les principales exportations d'Haïti sont :", choices: ["Le pétrole en grande quantité", "Les textiles (assemblage), les mangues, le café et le cacao", "L'électronique industrielle", "L'automobile"], answer: 1, note: "Exportations haïtiennes : textiles (assemblage, Zone Franche de Caracol), mangues Madame Francis (USA), café et cacao premium. Faible base d'exportation." },
    { q: "La mondialisation désigne :", choices: ["L'isolement économique des nations", "L'intégration croissante des économies, cultures et sociétés à l'échelle planétaire", "Le protectionnisme commercial", "La nationalisation des entreprises"], answer: 1, note: "Mondialisation : échanges commerciaux, financiers, culturels et humains à l'échelle mondiale. Accélérée depuis 1990 avec Internet, l'OMC et la libéralisation." },
    { q: "Le PIB (Produit Intérieur Brut) mesure :", choices: ["La richesse personnelle des citoyens", "La valeur totale des biens et services finaux produits sur le territoire national sur une période donnée", "Les exportations nettes uniquement", "Le niveau de vie moyen uniquement"], answer: 1, note: "PIB = C + I + G + (X-M). Haïti : PIB ~20 milliards USD (2023), un des plus bas des Amériques malgré l'aide internationale." },
    { q: "Les transferts de la diaspora haïtienne représentent :", choices: ["Moins de 5% du PIB", "Environ 30-40% du PIB haïtien — principale source de devises étrangères (~3-4 milliards$/an)", "10% du PIB uniquement", "Plus de 60% du PIB"], answer: 1, note: "Remesas haïtiennes : ~3-4 milliards USD/an. Principaux pays d'envoi : USA, Canada, France. Revenus vitaux pour des millions de familles haïtiennes." },
    { q: "Le Canal de Panama est important géographiquement car :", choices: ["Il sépare l'Amérique du Nord de l'Amérique du Sud", "Il relie l'Atlantique au Pacifique (80 km) — réduisant de ~15 000 km la route maritime mondiale", "C'est une frontière internationale", "Il alimente en eau la Colombie"], answer: 1, note: "Canal de Panama (inauguré 1914, élargi 2016) : ~14 000 navires/an. Crucial pour le commerce mondial. Impact direct sur le commerce caribéen." },
    { q: "L'IDH (Indice de Développement Humain) mesure :", choices: ["Uniquement le revenu par habitant", "Espérance de vie + niveau d'éducation + revenu par habitant (PIB/hab. en PPA)", "La puissance militaire", "Le PIB uniquement"], answer: 1, note: "IDH (PNUD) : 0 à 1. Haïti : IDH ~0,535 (2022) — 163ème sur 191 pays. Premier pays des Amériques dans la catégorie 'développement humain faible'." },
    { q: "La Zone Franche de Caracol au nord d'Haïti est :", choices: ["Une zone agricole protégée", "Un parc industriel pour l'assemblage textile — principal investissement étranger post-séisme 2010", "Une réserve naturelle", "Une zone touristique balnéaire"], answer: 1, note: "Caracol Industrial Park (2012) : plus grande zone franche haïtienne. Assemblage textile pour exportation USA (accord HOPE). ~15 000 emplois formels." },
    { q: "La déforestation en Haïti est principalement causée par :", choices: ["L'industrie forestière commerciale", "L'utilisation du charbon de bois (~80% des ménages comme combustible) + agriculture de subsistance", "Les cyclones tropicaux uniquement", "L'urbanisation principalement"], answer: 1, note: "Déforestation haïtienne : charbon de bois = principal combustible de cuisson → abattage massif. Résultat : ~2% de couvert forestier (vs 60% au 19e siècle)." },
    { q: "Le développement durable repose sur trois piliers :", choices: ["Économie, politique et culture", "Économique (croissance), Social (équité) et Environnemental (préservation) — rapport Brundtland (1987)", "PIB, IDH et HDI", "Commerce, industrie et agriculture"], answer: 1, note: "Développement durable (Brundtland, 1987) : 'répondre aux besoins du présent sans compromettre les générations futures'. 3 piliers : éco + social + environnemental." },
    { q: "La saison cyclonique dans les Caraïbes s'étend :", choices: ["De janvier à mars", "Du 1er juin au 30 novembre — pic en août-octobre", "Toute l'année", "De mars à juillet"], answer: 1, note: "Saison cyclonique Caraïbes : 1er juin - 30 novembre. Haïti très vulnérable : position géographique, déforestation, constructions fragiles, urbanisation anarchique." },
    { q: "La population d'Haïti est d'environ :", choices: ["5 millions d'habitants", "11-12 millions d'habitants (estimation 2023)", "20 millions d'habitants", "8 millions d'habitants"], answer: 1, note: "Population haïtienne : ~11-12 millions (2023). Croissance ~1,2%/an. Forte urbanisation (Port-au-Prince : ~40% population). Diaspora : 2-4 millions à l'étranger." },
    { q: "Les BRICS désignent :", choices: ["Les 5 pays les plus pauvres", "Brésil, Russie, Inde, Chine, Afrique du Sud — économies émergentes majeures à forte croissance", "Un traité commercial caribéen", "Les pays nordiques"], answer: 1, note: "BRICS (terme Goldman Sachs, 2001) : économies émergentes. Chine = 2ème PIB mondial (depuis 2010). Groupe élargi en 2024 (Éthiopie, Émirats, Arabie Saoudite...)." },
    { q: "L'Artibonite est surnommé :", choices: ["'La capitale touristique'", "'Le grenier d'Haïti' — principale région rizicole du pays", "'Le centre industriel'", "'Le pôle minier'"], answer: 1, note: "L'Artibonite : grenier d'Haïti. Production de riz, maïs, haricots. Département le plus peuplé d'Haïti (~1,7 million d'habitants). Centre agricole stratégique." },
    { q: "Le libre-échange est la politique qui :", choices: ["Protège les industries nationales par des droits de douane", "Supprime les barrières douanières pour favoriser les échanges commerciaux internationaux", "Nationalise les entreprises", "Réduit les importations"], answer: 1, note: "Libre-échange : absence de barrières tarifaires. OMC (1995) en est le principal promoteur. Haïti signataire des accords HOPE/HOPE II (textiles vers USA)." },
    { q: "La pollution marine dans la Caraïbe est principalement due à :", choices: ["Uniquement les plateformes pétrolières", "Les déchets plastiques, eaux usées non traitées, polluants agricoles et hydrocarbures (trafic maritime)", "Le tourisme uniquement", "Les activités militaires"], answer: 1, note: "Pollution marine caribéenne : plastiques, eaux usées (Haïti : <30% d'assainissement), pesticides, déversements pétroliers. Menace les récifs coralliens et la pêche." },
  ],

  // ============================================================
  // SMP → ANALYSE
  // ============================================================
  "Analyse": [
    { q: "La limite de f(x) = 3x + 2 quand x → 2 est :", choices: ["4", "6", "8", "10"], answer: 2, note: "lim(x→2)(3x+2) = 3(2)+2 = 8. Pour les polynômes, la limite s'obtient par substitution directe (continuité)." },
    { q: "La limite de f(x) = 1/x quand x → +∞ est :", choices: ["+∞", "0", "1", "-1"], answer: 1, note: "lim(x→+∞) 1/x = 0. Quand x → +∞, 1/x tend vers 0 par le bas (0⁺)." },
    { q: "La limite de f(x) = 1/x quand x → 0⁺ est :", choices: ["0", "+∞", "1", "-∞"], answer: 1, note: "lim(x→0⁺) 1/x = +∞. Quand x tend vers 0 par la droite (valeurs positives), 1/x tend vers +∞." },
    { q: "La limite remarquable lim(x→0) sin(x)/x = :", choices: ["0", "1", "∞", "indéfinie"], answer: 1, note: "lim(x→0) sin(x)/x = 1. Limite fondamentale en analyse. Démontrée par le théorème des gendarmes ou l'équivalent sin(x) ~ x en 0." },
    { q: "La limite lim(x→0) (eˣ - 1)/x = :", choices: ["0", "e", "1", "∞"], answer: 2, note: "lim(x→0) (eˣ-1)/x = 1. Limite remarquable fondamentale. C'est la dérivée de eˣ évaluée en x=0." },
    { q: "Une fonction f est continue en a si :", choices: ["f(a) existe uniquement", "f(a) existe, la limite en a existe et est égale à f(a)", "La limite seule existe", "f est dérivable en a"], answer: 1, note: "Continuité en a : (1) f(a) définie, (2) lim(x→a)f(x) existe, (3) lim = f(a). Polynômes, exp, ln, sin, cos : continues sur leur domaine." },
    { q: "Le nombre dérivé f'(a) est défini comme :", choices: ["f(a+h) - f(a)", "lim(h→0) [f(a+h) - f(a)]/h — limite du taux d'accroissement", "f(a)/h", "lim(h→0) f(a+h)"], answer: 1, note: "f'(a) : coefficient directeur de la tangente à la courbe au point d'abscisse a. Mesure le taux de variation instantané." },
    { q: "La dérivée de f(x) = xⁿ est :", choices: ["f'(x) = xⁿ⁻¹", "f'(x) = nxⁿ⁻¹", "f'(x) = nxⁿ", "f'(x) = xⁿ⁺¹"], answer: 1, note: "Règle des puissances : (xⁿ)' = nxⁿ⁻¹. Ex: (x⁵)' = 5x⁴, (x²)' = 2x, (x)' = 1, (constante)' = 0." },
    { q: "La dérivée de f(x) = eˣ est :", choices: ["f'(x) = xeˣ", "f'(x) = eˣ", "f'(x) = e", "f'(x) = ln(x)"], answer: 1, note: "(eˣ)' = eˣ. L'exponentielle est la seule fonction (à constante multiplicative près) égale à sa dérivée." },
    { q: "La dérivée de f(x) = ln(x) est :", choices: ["f'(x) = 1/x²", "f'(x) = 1/x (pour x > 0)", "f'(x) = x", "f'(x) = e/x"], answer: 1, note: "(ln x)' = 1/x pour x > 0. Plus généralement : (ln|u|)' = u'/u." },
    { q: "La règle de la chaîne : (f∘g)'(x) = :", choices: ["f'(x) × g'(x)", "f'(g(x)) × g'(x)", "f(g'(x))", "f'(g'(x))"], answer: 1, note: "Règle de la chaîne : dériver la fonction externe évaluée en g(x), multiplier par la dérivée de g(x). Ex: (sin(x²))' = cos(x²) × 2x." },
    { q: "La règle du produit : (fg)'(x) = :", choices: ["f'(x) × g'(x)", "f'(x)g(x) + f(x)g'(x)", "f'(x)/g(x)", "f(x) × g'(x)"], answer: 1, note: "(fg)' = f'g + fg'. Ex: (x²·sin x)' = 2x·sin x + x²·cos x." },
    { q: "Si f'(x) > 0 sur ]a,b[, alors f est :", choices: ["Décroissante sur ]a,b[", "Croissante sur ]a,b[", "Constante", "Nulle"], answer: 1, note: "f' > 0 → f croissante. f' < 0 → f décroissante. f' = 0 partout → f constante. Base de l'étude des variations." },
    { q: "Un maximum local de f en x₀ se reconnaît quand :", choices: ["f(x₀) = 0", "f'(x₀) = 0 et f' change de signe de + vers −", "f''(x₀) = 0 toujours", "f est continue en x₀"], answer: 1, note: "Maximum local : f'(x₀) = 0 et f' passe de + à − en x₀. Test de la dérivée seconde : si f''(x₀) < 0 → maximum local." },
    { q: "L'équation de la tangente à la courbe de f au point (a, f(a)) est :", choices: ["y = f(a)", "y = f'(a)(x - a) + f(a)", "y = f(a)(x - a)", "y = f''(a)·x + f(a)"], answer: 1, note: "Tangente en (a, f(a)) : y = f'(a)(x-a) + f(a). Le coefficient directeur est le nombre dérivé f'(a)." },
    { q: "∫ xⁿ dx (n ≠ -1) = :", choices: ["xⁿ⁺¹ + C", "xⁿ⁺¹/(n+1) + C", "(n+1)xⁿ + C", "xⁿ⁻¹/(n-1) + C"], answer: 1, note: "Formule d'intégration des puissances : ∫xⁿdx = xⁿ⁺¹/(n+1) + C (n ≠ -1). La constante C représente la famille de primitives." },
    { q: "∫ (1/x) dx = :", choices: ["1/x² + C", "ln|x| + C", "x + C", "-1/x + C"], answer: 1, note: "∫ 1/x dx = ln|x| + C. La valeur absolue est nécessaire car ln est défini pour x > 0 mais 1/x est aussi définie pour x < 0." },
    { q: "Le Théorème Fondamental du Calcul Intégral énonce :", choices: ["Toute fonction intégrable a une primitive", "Si F est primitive de f sur [a,b], alors ∫ₐᵇ f(x)dx = F(b) - F(a)", "L'intégrale est toujours positive", "Dérivée et intégrale n'ont aucun lien"], answer: 1, note: "TFC : ∫ₐᵇ f(x)dx = [F(x)]ₐᵇ = F(b) - F(a). Fait le lien fondamental entre dérivation et intégration (Newton-Leibniz)." },
    { q: "∫₀π sin(x) dx = :", choices: ["0", "1", "2", "π"], answer: 2, note: "∫₀π sin(x)dx = [-cos(x)]₀π = -cos(π) - (-cos 0) = 1+1 = 2." },
    { q: "L'intégrale définie ∫ₐᵇ f(x)dx représente géométriquement :", choices: ["La longueur de la courbe", "L'aire algébrique entre la courbe et l'axe des abscisses entre a et b", "La pente de la tangente", "La valeur maximale de f"], answer: 1, note: "∫ₐᵇ f(x)dx = aire algébrique. f(x)≥0 : aire positive. f(x)≤0 : aire négative. Pour l'aire totale, prendre la valeur absolue de chaque portion." },
    { q: "Le Théorème de Rolle : si f continue sur [a,b], dérivable sur ]a,b[ et f(a)=f(b), alors :", choices: ["f est constante sur [a,b]", "Il existe c ∈ ]a,b[ tel que f'(c) = 0", "f est nulle sur [a,b]", "f' est toujours positive"], answer: 1, note: "Théorème de Rolle : si f 'repart' du même niveau (f(a)=f(b)), il y a au moins un point où la tangente est horizontale." },
    { q: "Le Théorème des Valeurs Intermédiaires (TVI) affirme :", choices: ["Toute fonction continue est dérivable", "Si f est continue sur [a,b] et k est entre f(a) et f(b), il existe c tel que f(c)=k", "La dérivée d'une continue est nulle", "Toute continue admet un maximum"], answer: 1, note: "TVI : une fonction continue prend toutes les valeurs entre f(a) et f(b). Application : méthode de dichotomie pour trouver des racines." },
    { q: "L'intégration par parties est :", choices: ["∫u·v dx = u·v + C", "∫u·v' dx = u·v - ∫v·u' dx", "∫u·v dx = u'·v'", "∫u·v' dx = u'·v"], answer: 1, note: "IPP : ∫u·v'dx = [u·v] - ∫v·u'dx. Utile pour ∫x·eˣdx, ∫x·sinxdx, ∫ln(x)dx, ∫eˣ·cos(x)dx..." },
    { q: "La dérivée de f(x) = sin(x) est :", choices: ["f'(x) = -cos(x)", "f'(x) = cos(x)", "f'(x) = -sin(x)", "f'(x) = tan(x)"], answer: 1, note: "Cycle des dérivées trigonométriques : sin → cos → -sin → -cos → sin... (période 4)." },
    { q: "La dérivée de f(x) = tan(x) est :", choices: ["f'(x) = -1/cos²(x)", "f'(x) = 1/cos²(x) = 1 + tan²(x)", "f'(x) = -sin(x)/cos(x)", "f'(x) = cos²(x)"], answer: 1, note: "(tan x)' = 1/cos²(x). Domaine : x ≠ π/2 + kπ." },
    { q: "La limite lim(n→+∞) (1 + 1/n)ⁿ = :", choices: ["1", "∞", "e ≈ 2,71828...", "2"], answer: 2, note: "lim(n→+∞) (1+1/n)ⁿ = e. Définition du nombre e (nombre d'Euler). Fondement de la fonction exponentielle." },
    { q: "Une fonction f est paire si :", choices: ["f(-x) = f(x) pour tout x du domaine — symétrie par rapport à l'axe des ordonnées", "f(-x) = -f(x)", "f(x) = f(x+1)", "f(0) = 0"], answer: 0, note: "Fonction paire : f(-x) = f(x). Courbe symétrique par rapport à l'axe Oy. Ex: cos(x), x², |x|." },
    { q: "Une fonction f est impaire si :", choices: ["f(-x) = f(x)", "f(-x) = -f(x) pour tout x — symétrie par rapport à l'origine O", "f(x) = f(x+1)", "f(0) ≠ 0"], answer: 1, note: "Fonction impaire : f(-x) = -f(x). Courbe symétrique par rapport à l'origine O. Ex: sin(x), x, x³." },
  ],

  // ============================================================
  // SMP → SUITE
  // ============================================================
  "Suite": [
    { q: "Une suite numérique est :", choices: ["Une fonction définie sur ℝ", "Une application de ℕ vers ℝ — liste ordonnée de termes (uₙ)ₙ∈ℕ", "Un graphe de fonction", "Une série infinie uniquement"], answer: 1, note: "Suite (uₙ) : application n ↦ uₙ de ℕ vers ℝ. Ex: uₙ = 2n+1 donne 1, 3, 5, 7, 9... (suite explicite)." },
    { q: "Une suite est définie par récurrence quand :", choices: ["On donne une formule explicite uₙ = f(n)", "On donne le premier terme et une relation uₙ₊₁ = f(uₙ)", "On donne tous les termes listés", "On donne la somme des termes"], answer: 1, note: "Récurrence : ex: u₀ = 1, uₙ₊₁ = 2uₙ + 1. u₁ = 3, u₂ = 7, u₃ = 15... Plus difficile à calculer qu'une formule explicite." },
    { q: "Une suite arithmétique est caractérisée par :", choices: ["Un rapport constant entre termes consécutifs", "Une différence constante r entre termes consécutifs : uₙ₊₁ = uₙ + r", "Des termes de plus en plus grands toujours", "Une formule explicite quadratique"], answer: 1, note: "Suite arithmétique : uₙ₊₁ - uₙ = r (raison). r > 0 → croissante. r < 0 → décroissante. r = 0 → constante." },
    { q: "Le terme général d'une suite arithmétique (u₀, raison r) est :", choices: ["uₙ = u₀ × rⁿ", "uₙ = u₀ + n·r", "uₙ = u₀ × n", "uₙ = u₀ + r"], answer: 1, note: "Suite arithmétique : uₙ = u₀ + n·r. Si premier terme = u₁ : uₙ = u₁ + (n-1)·r." },
    { q: "La somme des n premiers termes d'une suite arithmétique est :", choices: ["Sₙ = n × u₀", "Sₙ = n × (premier terme + dernier terme)/2", "Sₙ = u₀ × rⁿ", "Sₙ = n²·r/2"], answer: 1, note: "Somme arithmétique : Sₙ = n × (u₀ + uₙ₋₁)/2. Ex: 1+2+...+100 = 100×(1+100)/2 = 5050 (Gauss)." },
    { q: "Si u₃ = 7 et u₇ = 15 dans une suite arithmétique, la raison r est :", choices: ["2", "8", "4", "1"], answer: 0, note: "u₇ - u₃ = 4r = 15-7 = 8 → r = 2. Formule générale : r = (uₙ - uₘ)/(n-m)." },
    { q: "Une suite géométrique est caractérisée par :", choices: ["Une différence constante entre termes", "Un rapport constant q entre termes consécutifs : uₙ₊₁ = uₙ × q", "Des termes toujours positifs", "Une formule additive"], answer: 1, note: "Suite géométrique : uₙ₊₁/uₙ = q (raison). Ex: 2, 6, 18, 54... (q=3). Ex: 100, 50, 25... (q=1/2)." },
    { q: "Le terme général d'une suite géométrique (u₀, raison q) est :", choices: ["uₙ = u₀ + n·q", "uₙ = u₀ × qⁿ", "uₙ = u₀ × n × q", "uₙ = u₀/q"], answer: 1, note: "Suite géométrique : uₙ = u₀ × qⁿ. Ex: u₀ = 3, q = 2 → u₅ = 3 × 2⁵ = 96." },
    { q: "La somme des n premiers termes d'une suite géométrique (q ≠ 1) est :", choices: ["Sₙ = n × u₀ × q", "Sₙ = u₀ × (1 - qⁿ)/(1 - q)", "Sₙ = u₀ + n × q", "Sₙ = u₀ × n"], answer: 1, note: "Sₙ = u₀(1-qⁿ)/(1-q) pour q ≠ 1. Si q = 1 : Sₙ = n × u₀." },
    { q: "Si |q| < 1, la suite géométrique (uₙ = u₀ × qⁿ) :", choices: ["Diverge vers l'infini", "Converge vers 0", "Reste constante", "Oscille infiniment"], answer: 1, note: "Si |q| < 1 : |qⁿ| → 0. Donc uₙ = u₀ × qⁿ → 0. Ex: (1/2)ⁿ → 0. Modélise la décroissance exponentielle (désintégration, dépréciation)." },
    { q: "Si q > 1 et u₀ > 0, la suite géométrique :", choices: ["Converge vers 0", "Diverge vers +∞", "Reste bornée", "Oscille"], answer: 1, note: "q > 1, u₀ > 0 → uₙ → +∞. Croissance exponentielle. Ex: placement financier avec taux > 0 → croissance illimitée (modèle théorique)." },
    { q: "La suite uₙ = (-1)ⁿ est :", choices: ["Convergente vers 0", "Divergente (oscille entre -1 et 1 sans limite)", "Croissante", "Convergente vers 1"], answer: 1, note: "(-1)ⁿ : 1, -1, 1, -1... → oscille. Pas de limite → suite divergente." },
    { q: "Une suite croissante et bornée supérieurement :", choices: ["Diverge toujours", "Converge (théorème de la limite monotone)", "Oscille indéfiniment", "Est constante"], answer: 1, note: "Théorème de la limite monotone : toute suite monotone bornée converge. Ex: uₙ = 1-1/n est croissante et bornée par 1 → converge vers 1." },
    { q: "La suite uₙ = 2n/(3n+1) tend vers :", choices: ["0", "2/3", "2", "∞"], answer: 1, note: "lim 2n/(3n+1) = lim 2/(3+1/n) = 2/3. Méthode : diviser numérateur et dénominateur par n (terme dominant)." },
    { q: "Le théorème des gendarmes dit que si vₙ ≤ uₙ ≤ wₙ et lim vₙ = lim wₙ = L, alors :", choices: ["uₙ diverge", "lim uₙ = L", "lim uₙ = 0", "uₙ oscille"], answer: 1, note: "Théorème sandwich : si uₙ est 'coincée' entre deux suites convergeant vers L, elle converge aussi vers L." },
    { q: "La somme 1 + 2 + 3 + ... + 100 = :", choices: ["5 050", "10 100", "1 000", "100×51"], answer: 0, note: "Gauss : Sₙ = n(n+1)/2. S₁₀₀ = 100×101/2 = 5050. Méthode : 50 paires (1+100) = 5050." },
    { q: "La suite uₙ = 1/n converge vers :", choices: ["1", "0", "+∞", "e"], answer: 1, note: "lim(n→+∞) 1/n = 0. Suite décroissante, positive, minorée par 0 → convergente vers 0." },
    { q: "La somme géométrique infinie (|q|<1) : u₀ + u₀q + u₀q² + ... = :", choices: ["2u₀", "u₀/(1-q)", "u₀×q/(1-q)", "∞"], answer: 1, note: "Série géométrique convergente (|q|<1) : S∞ = u₀/(1-q). Ex: 1 + 1/2 + 1/4 + ... = 1/(1-1/2) = 2." },
    { q: "Dans une suite arithmétique de raison r, u₁₀ - u₃ = :", choices: ["7r", "10r - 3r = 7r", "3r", "10r"], answer: 0, note: "uₙ - uₘ = (n-m)r. u₁₀ - u₃ = (10-3)r = 7r." },
    { q: "La suite uₙ = n² + 3n + 1 tend vers :", choices: ["3", "+∞", "0", "1"], answer: 1, note: "lim(n→+∞) (n²+3n+1) = +∞. Les polynômes de degré ≥ 1 à coefficient dominant positif tendent vers +∞." },
  ],

  // ============================================================
  // SMP → COMPLEXE
  // ============================================================
  "Complexe": [
    { q: "L'unité imaginaire i est définie par :", choices: ["i = √1", "i² = -1 (i est le nombre dont le carré vaut -1)", "i = 0", "i = √2"], answer: 1, note: "i² = -1. i n'est pas réel (√(-1) n'existe pas dans ℝ). i est la base de l'ensemble des complexes ℂ." },
    { q: "Un nombre complexe z = a + bi est :", choices: ["Un nombre réel si b ≠ 0", "La somme d'une partie réelle a (Re(z)) et d'une partie imaginaire b (Im(z))", "Toujours négatif", "Impossible à calculer"], answer: 1, note: "z = a + bi : a = Re(z) = partie réelle, b = Im(z) = partie imaginaire. Si b=0 : réel. Si a=0 : imaginaire pur." },
    { q: "i² = :", choices: ["1", "i", "-1", "0"], answer: 2, note: "Par définition : i² = -1. Conséquences : i³ = -i, i⁴ = 1, i⁵ = i. Cycle de période 4." },
    { q: "i³ = :", choices: ["i", "-i", "1", "-1"], answer: 1, note: "i³ = i²·i = (-1)·i = -i. Cycle : i¹=i, i²=-1, i³=-i, i⁴=1, puis recommence." },
    { q: "Le conjugué de z = 3 + 4i est :", choices: ["z̄ = 3 + 4i", "z̄ = 3 - 4i", "z̄ = -3 + 4i", "z̄ = -3 - 4i"], answer: 1, note: "Conjugué : z̄ = a - bi (on change le signe de la partie imaginaire). z·z̄ = a² + b² = |z|² (réel positif)." },
    { q: "Le module de z = 3 + 4i est :", choices: ["|z| = 7", "|z| = √(9+16) = 5", "|z| = 3", "|z| = 4"], answer: 1, note: "|z| = √(a²+b²). Pour z = 3+4i : |z| = √(9+16) = √25 = 5. Triangle pythagoricien 3-4-5." },
    { q: "Le module |z| = √(a² + b²) représente :", choices: ["La partie réelle", "La distance de z à l'origine dans le plan complexe (plan d'Argand)", "La partie imaginaire", "L'argument de z"], answer: 1, note: "|z| = distance de M(a,b) à l'origine O dans le plan d'Argand-Gauss. |z| ≥ 0, et |z| = 0 ssi z = 0." },
    { q: "L'argument θ d'un complexe z est :", choices: ["Son module |z|", "L'angle orienté entre l'axe réel positif et le vecteur OM — z = |z|(cosθ + i·sinθ)", "Sa partie réelle", "Son inverse"], answer: 1, note: "Argument θ ∈ ]-π, π]. Forme trigonométrique : z = r(cosθ + i sinθ) avec r = |z|. Ex: z = 1+i : r=√2, θ=π/4." },
    { q: "La formule d'Euler est :", choices: ["eˣ = cos(x) + sin(x)", "e^(iθ) = cos(θ) + i·sin(θ)", "e^(iθ) = cos(θ) - i·sin(θ)", "e^(iθ) = sin(θ) + i·cos(θ)"], answer: 1, note: "Formule d'Euler : e^(iθ) = cosθ + i·sinθ. Donc z = r·e^(iθ). Identité d'Euler : e^(iπ)+1 = 0 (relie e, i, π, 1, 0)." },
    { q: "Le produit de z₁ = r₁e^(iθ₁) et z₂ = r₂e^(iθ₂) donne :", choices: ["|z₁z₂| = |z₁|/|z₂|", "|z₁z₂| = |z₁|×|z₂| et arg(z₁z₂) = θ₁ + θ₂", "|z₁z₂| = |z₁|+|z₂|", "|z₁z₂| = |z₁|²×|z₂|²"], answer: 1, note: "Multiplication : modules multipliés, arguments additionnés. z₁z₂ = r₁r₂·e^(i(θ₁+θ₂))." },
    { q: "L'équation z² = -1 a pour solutions dans ℂ :", choices: ["z = ±1", "z = ±i", "Pas de solutions", "z = 0"], answer: 1, note: "z² = -1 → z = ±i. Vérification : i² = -1 ✓ et (-i)² = (-1)²i² = i² = -1 ✓. Pas de solutions dans ℝ." },
    { q: "Si Δ = b²-4ac < 0 pour az²+bz+c = 0, les racines sont :", choices: ["Deux réelles distinctes", "z = (-b ± i√|Δ|)/(2a) — deux complexes conjuguées", "Une racine double réelle", "Pas de racines du tout"], answer: 1, note: "Δ < 0 : z = (-b ± i√|Δ|)/(2a). Les deux racines sont complexes conjuguées. Ex: z²+1=0 → z = ±i." },
    { q: "z + z̄ = :", choices: ["0", "2·Re(z) = 2a", "2·Im(z)", "|z|²"], answer: 1, note: "z + z̄ = (a+bi) + (a-bi) = 2a = 2·Re(z). Les parties imaginaires s'annulent." },
    { q: "z × z̄ = :", choices: ["0", "|z|² = a² + b² (réel positif)", "2bi", "a²-b²"], answer: 1, note: "z·z̄ = (a+bi)(a-bi) = a²+b² = |z|². Résultat toujours réel positif. Utile pour calculer 1/z = z̄/|z|²." },
    { q: "La formule de De Moivre : (cosθ + i sinθ)ⁿ = :", choices: ["cos(nθ) + i sin(nθ)", "n(cosθ + i sinθ)", "cos(θ/n) + i sin(θ/n)", "cos²θ + sin²θ"], answer: 0, note: "De Moivre : (e^(iθ))ⁿ = e^(inθ) → (cosθ + i sinθ)ⁿ = cos(nθ) + i sin(nθ). Utile pour cos(nθ) et sin(nθ) en termes de cosθ, sinθ." },
    { q: "L'ensemble ℂ des complexes contient :", choices: ["Uniquement les imaginaires purs", "ℝ ⊂ ℂ : tout réel a est le complexe a+0i — ℂ étend ℝ", "Uniquement les nombres avec |z|=1", "Les réels séparément des imaginaires"], answer: 1, note: "ℝ ⊂ ℂ : les réels sont les complexes avec b=0. ℂ étend ℝ en ajoutant les solutions d'équations comme x²+1=0." },
    { q: "La forme trigonométrique de z = 1 + i est :", choices: ["z = √2(cos(π/3) + i sin(π/3))", "z = √2(cos(π/4) + i sin(π/4))", "z = 2(cos(π/4) + i sin(π/4))", "z = (cos(π/4) + i sin(π/4))"], answer: 1, note: "|1+i| = √(1+1) = √2. arg(1+i) = π/4 (angle de 45°). z = √2·e^(iπ/4) = √2(cos(π/4) + i sin(π/4))." },
    { q: "Le quotient 1/z (z ≠ 0) en termes de z̄ et |z|² est :", choices: ["1/z = z̄", "1/z = z̄/|z|²", "1/z = |z|/z̄", "1/z = -z̄"], answer: 1, note: "1/z = z̄/(z·z̄) = z̄/|z|². Méthode de division complexe : multiplier par le conjugué du dénominateur." },
    { q: "Les racines nièmes de l'unité sont les solutions de :", choices: ["z² = 1", "zⁿ = 1 — il y a exactement n solutions dans ℂ régulièrement espacées sur le cercle unité", "z = n", "nz = 1"], answer: 1, note: "Racines nièmes de l'unité : zₖ = e^(2iπk/n) pour k = 0, 1, ..., n-1. Forment un polygone régulier à n sommets sur le cercle unité." },
  ],

  // ============================================================
  // SMP → PROBABILITÉ
  // ============================================================
  "Probabilité": [
    { q: "La probabilité P(A) d'un événement A vérifie :", choices: ["P(A) peut être négatif", "0 ≤ P(A) ≤ 1, P(∅) = 0 et P(Ω) = 1", "P(A) > 1 si A est certain", "P(A) = 1/2 toujours"], answer: 1, note: "Axiomes de Kolmogorov : P(A) ∈ [0,1]. P(∅) = 0 (impossible). P(Ω) = 1 (certain). Fondements de la théorie des probabilités." },
    { q: "Si A et B sont incompatibles (A∩B = ∅), alors :", choices: ["P(A∪B) = P(A)×P(B)", "P(A∪B) = P(A) + P(B)", "P(A∩B) = P(A) + P(B)", "P(A∪B) = P(A) - P(B)"], answer: 1, note: "Incompatibles : P(A∪B) = P(A)+P(B). Ex: face et pile d'une pièce — événements incompatibles, P = 1/2 + 1/2 = 1." },
    { q: "La formule générale de l'union : P(A∪B) = :", choices: ["P(A) + P(B)", "P(A) + P(B) - P(A∩B)", "P(A) × P(B)", "P(A) - P(B) + P(A∩B)"], answer: 1, note: "P(A∪B) = P(A)+P(B)-P(A∩B). On soustrait P(A∩B) pour ne pas compter deux fois les événements communs." },
    { q: "L'événement complémentaire Ā vérifie :", choices: ["P(Ā) = P(A)", "P(Ā) = 1 - P(A)", "P(Ā) = 1/P(A)", "P(A) + P(Ā) = 0"], answer: 1, note: "P(Ā) = 1 - P(A). Car A et Ā sont incompatibles et exhaustifs : P(A) + P(Ā) = 1." },
    { q: "Si A et B sont indépendants, alors :", choices: ["P(A∩B) = P(A) + P(B)", "P(A∩B) = P(A) × P(B)", "P(A|B) = P(B)", "P(A∪B) = P(A) × P(B)"], answer: 1, note: "Indépendance : la réalisation de B ne modifie pas la probabilité de A. P(A∩B) = P(A)×P(B)." },
    { q: "La probabilité conditionnelle P(A|B) est :", choices: ["P(A) + P(B)", "P(A∩B) / P(B) — probabilité de A sachant que B est réalisé (P(B) > 0)", "P(A) / P(B)", "P(A) × P(B)"], answer: 1, note: "P(A|B) = P(A∩B)/P(B). Ex: P(malade|testé positif) — probabilité d'être malade sachant que le test est positif." },
    { q: "La formule des probabilités totales (partition B, B̄) donne :", choices: ["P(A) = P(A|B)", "P(A) = P(A|B)×P(B) + P(A|B̄)×P(B̄)", "P(A) = P(B) + P(B̄)", "P(A) = P(A∩B)²"], answer: 1, note: "Probabilités totales : P(A) = Σ P(A|Bᵢ)P(Bᵢ) pour toute partition {Bᵢ} de Ω. Utile quand on dispose de plusieurs 'chemins' pour arriver à A." },
    { q: "Le théorème de Bayes permet de :", choices: ["Calculer la probabilité de l'union", "Inverser une probabilité conditionnelle : P(B|A) = P(A|B)×P(B) / P(A)", "Vérifier l'indépendance", "Calculer le module d'un complexe"], answer: 1, note: "Bayes : P(B|A) = P(A|B)P(B)/P(A). Fondement des statistiques bayésiennes, diagnostic médical, IA (classification naive de Bayes)." },
    { q: "L'espérance mathématique E(X) d'une variable aléatoire discrète est :", choices: ["La valeur la plus fréquente (mode)", "E(X) = Σ xᵢ × P(X=xᵢ) — valeur moyenne théorique", "La valeur médiane", "La valeur maximale"], answer: 1, note: "E(X) = Σ xᵢ·pᵢ. Ex: X = gain d'un jeu, P(X=10)=0,3, P(X=-5)=0,7 → E(X) = 10×0,3 + (-5)×0,7 = 3-3,5 = -0,5." },
    { q: "La variance V(X) mesure :", choices: ["La valeur centrale", "La dispersion des valeurs autour de la moyenne — V(X) = E(X²) - [E(X)]²", "L'espérance", "La probabilité maximale"], answer: 1, note: "V(X) = E[(X-μ)²] = E(X²) - [E(X)]². Toujours ≥ 0. V(X) = 0 ssi X est constante." },
    { q: "L'écart-type σ(X) est :", choices: ["σ = V(X)", "σ = √V(X) — dispersion dans la même unité que X", "σ = E(X)", "σ = V(X)²"], answer: 1, note: "Écart-type σ = √V(X). Même unité que X (contrairement à la variance en unité²). Plus σ est grand, plus les valeurs sont dispersées." },
    { q: "Une épreuve de Bernoulli est :", choices: ["Une série de 100 lancers", "Une épreuve à deux résultats : succès (probabilité p) et échec (probabilité q = 1-p)", "Un lancer de dé à 6 faces", "Un tirage avec remise de n boules"], answer: 1, note: "Bernoulli : succès (P=p) ou échec (P=1-p). Ex: lancer une pièce, tester un médicament, vérifier si une pièce est défectueuse." },
    { q: "La loi binomiale B(n,p) modélise :", choices: ["Une seule épreuve de Bernoulli", "Le nombre de succès X dans n épreuves de Bernoulli indépendantes de même paramètre p", "Une distribution continue", "La loi normale"], answer: 1, note: "X ~ B(n,p) : P(X=k) = C(n,k)·pᵏ·(1-p)^(n-k). E(X) = np, V(X) = np(1-p). Ex: nombre de piles en 10 lancers." },
    { q: "Si X ~ B(n,p), l'espérance E(X) et la variance V(X) sont :", choices: ["E(X) = n, V(X) = p", "E(X) = np, V(X) = np(1-p) = npq", "E(X) = np², V(X) = np", "E(X) = n/p, V(X) = np²"], answer: 1, note: "Binomiale : E(X) = np, V(X) = npq = np(1-p). Ex: 20 lancers, p=1/6 → E(X) = 20/6 ≈ 3,33." },
    { q: "P(X=k) pour X ~ B(n,p) est :", choices: ["p^k", "C(n,k) × p^k × (1-p)^(n-k)", "n × p^k", "C(n,k) × p^(n-k)"], answer: 1, note: "Formule binomiale : P(X=k) = C(n,k)·pᵏ·qⁿ⁻ᵏ avec q=1-p et k ∈ {0,1,...,n}." },
    { q: "La combinaison C(n,k) = :", choices: ["n!/k!", "n!/(k!(n-k)!)", "n×k", "(n+k)!/(n!k!)"], answer: 1, note: "C(n,k) = n!/(k!(n-k)!) = 'n parmi k'. Nombre de façons de choisir k éléments parmi n sans ordre. Ex: C(5,2) = 10." },
    { q: "P(X ≥ 1) se calcule par :", choices: ["Σ P(X=k) pour k=1 à n directement", "1 - P(X=0) — méthode du complémentaire", "P(X=1) uniquement", "Impossible à calculer directement"], answer: 1, note: "P(X≥1) = 1 - P(X=0) = 1 - q^n. La méthode du complémentaire est souvent plus rapide que la somme directe." },
    { q: "La loi des grands nombres affirme que :", choices: ["Toutes les expériences donnent le même résultat", "La fréquence observée converge vers la probabilité théorique quand n → ∞", "Les probabilités sont des fréquences exactes", "Plus on répète, plus les résultats sont différents"], answer: 1, note: "Loi des grands nombres : fₙ(A) → P(A) quand n → ∞. Fondement du lien entre probabilité théorique et fréquence expérimentale." },
    { q: "Dans un lancer de dé équilibré à 6 faces, P({4}) = :", choices: ["1/4", "1/6", "4/6", "1/3"], answer: 1, note: "Probabilité classique (équiprobabilité) : P(A) = cas favorables / cas possibles = 1/6." },
    { q: "La médiane d'une série statistique est :", choices: ["La valeur la plus fréquente (mode)", "La valeur qui partage la série en deux moitiés égales — 50% en dessous, 50% au-dessus", "La moyenne arithmétique", "La valeur maximale"], answer: 1, note: "Médiane : Q₂. Moins sensible aux valeurs extrêmes que la moyenne. Préférable pour les revenus, prix immobiliers (distributions asymétriques)." },
  ],

  // ============================================================
  // SMP → GÉOMÉTRIE
  // ============================================================
  "Géométrie": [
    { q: "La distance entre deux points A(x₁,y₁) et B(x₂,y₂) est :", choices: ["AB = |x₂-x₁| + |y₂-y₁|", "AB = √((x₂-x₁)² + (y₂-y₁)²)", "AB = (x₂-x₁)² + (y₂-y₁)²", "AB = (x₂+x₁)/2"], answer: 1, note: "Distance AB = √((x₂-x₁)²+(y₂-y₁)²). Application directe du théorème de Pythagore dans le plan cartésien." },
    { q: "Le milieu I du segment [AB] avec A(x₁,y₁) et B(x₂,y₂) est :", choices: ["I((x₁-x₂)/2, (y₁-y₂)/2)", "I((x₁+x₂)/2, (y₁+y₂)/2)", "I(x₁+x₂, y₁+y₂)", "I(x₁×x₂, y₁×y₂)"], answer: 1, note: "Milieu : coordonnées = moyennes des coordonnées des extrémités." },
    { q: "L'équation d'une droite de pente a et d'ordonnée à l'origine b est :", choices: ["x = ay + b", "y = ax + b", "y = a/x + b", "ay = x + b"], answer: 1, note: "y = ax + b. a = coefficient directeur (pente). b = ordonnée à l'origine (valeur en x=0)." },
    { q: "Le coefficient directeur (pente) de la droite passant par A(x₁,y₁) et B(x₂,y₂) est :", choices: ["a = (y₂+y₁)/(x₂+x₁)", "a = (y₂-y₁)/(x₂-x₁)", "a = (x₂-x₁)/(y₂-y₁)", "a = |y₂-y₁|"], answer: 1, note: "a = Δy/Δx. Mesure la variation de y par unité de x. Pente nulle = droite horizontale. Pente infinie = droite verticale." },
    { q: "Deux droites de pentes a₁ et a₂ sont perpendiculaires si :", choices: ["a₁ = a₂", "a₁ × a₂ = -1", "a₁ + a₂ = 0", "a₁ = -a₂"], answer: 1, note: "Perpendicularité : a₁×a₂ = -1. Ex: pentes 2 et -1/2 → 2×(-1/2) = -1 ✓. Droites d'équations y=2x+1 et y=-x/2+3 sont perpendiculaires." },
    { q: "L'équation d'un cercle de centre C(a,b) et de rayon r est :", choices: ["(x+a)² + (y+b)² = r", "(x-a)² + (y-b)² = r²", "x² + y² = r", "(x-a) + (y-b) = r"], answer: 1, note: "Cercle : (x-a)²+(y-b)² = r². Ensemble des points à distance r du centre C(a,b). Si C = O : x²+y² = r²." },
    { q: "Le vecteur AB⃗ avec A(x₁,y₁) et B(x₂,y₂) a pour composantes :", choices: ["AB⃗ = (x₁-x₂, y₁-y₂)", "AB⃗ = (x₂-x₁, y₂-y₁)", "AB⃗ = (x₂+x₁, y₂+y₁)", "AB⃗ = (x₁×x₂, y₁×y₂)"], answer: 1, note: "AB⃗ = (x₂-x₁, y₂-y₁). Vecteur = différence des coordonnées du point d'arrivée moins le point de départ." },
    { q: "Le produit scalaire u⃗(a,b)·v⃗(c,d) est :", choices: ["u⃗·v⃗ = ac - bd", "u⃗·v⃗ = ac + bd", "u⃗·v⃗ = (a+c)(b+d)", "u⃗·v⃗ = a²+b²+c²+d²"], answer: 1, note: "u⃗·v⃗ = ac+bd. Aussi : u⃗·v⃗ = |u⃗||v⃗|cosθ où θ est l'angle entre les vecteurs." },
    { q: "Deux vecteurs u⃗ et v⃗ sont orthogonaux si :", choices: ["Ils ont la même norme", "u⃗·v⃗ = 0 (produit scalaire nul)", "u⃗ + v⃗ = 0", "Ils ont la même direction"], answer: 1, note: "u⃗⊥v⃗ ⟺ u⃗·v⃗ = 0 ⟺ cosθ = 0 ⟺ θ = 90°." },
    { q: "Le théorème de Pythagore dans le triangle ABC rectangle en C est :", choices: ["AB = AC + BC", "AB² = AC² + BC²", "AC² = AB² + BC²", "AB² = AC² - BC²"], answer: 1, note: "Pythagore : hypoténuse² = somme des carrés des deux cathètes. AB (hypoténuse) est le côté opposé à l'angle droit C." },
    { q: "La relation fondamentale de la trigonométrie est :", choices: ["sin(x) + cos(x) = 1", "sin²(x) + cos²(x) = 1", "sin(x) × cos(x) = 1", "tan(x) = sin(x) + cos(x)"], answer: 1, note: "sin²x + cos²x = 1. Identité pythagoricienne — découle directement du théorème de Pythagore sur le cercle unité." },
    { q: "cos(60°) = cos(π/3) = :", choices: ["√3/2", "1/2", "1", "√2/2"], answer: 1, note: "Valeurs remarquables : cos(0°)=1, cos(30°)=√3/2, cos(45°)=√2/2, cos(60°)=1/2, cos(90°)=0." },
    { q: "sin(30°) = sin(π/6) = :", choices: ["√3/2", "1/2", "1", "√2/2"], answer: 1, note: "Valeurs : sin(0°)=0, sin(30°)=1/2, sin(45°)=√2/2, sin(60°)=√3/2, sin(90°)=1." },
    { q: "L'aire d'un triangle de base b et de hauteur h est :", choices: ["A = b × h", "A = b × h / 2", "A = b² × h", "A = (b+h)/2"], answer: 1, note: "Aire triangle = base × hauteur / 2. Si 3 côtés connus : formule de Héron. Aussi : A = (1/2)|AB⃗ × AC⃗|." },
    { q: "L'aire d'un disque de rayon r est :", choices: ["A = 2πr", "A = πr²", "A = πr", "A = 4πr²"], answer: 1, note: "Aire disque = πr². Périmètre du cercle = 2πr. Volume sphère = (4/3)πr³. Surface sphère = 4πr²." },
    { q: "Dans un repère, la translation de vecteur u⃗(a,b) transforme M(x,y) en :", choices: ["M'(x-a, y-b)", "M'(x+a, y+b)", "M'(xa, yb)", "M'(a/x, b/y)"], answer: 1, note: "Translation : M(x,y) → M'(x+a, y+b). Les coordonnées augmentent des composantes du vecteur." },
    { q: "Le théorème de Thalès (angle inscrit dans un demi-cercle) stipule :", choices: ["L'angle inscrit est de 45°", "Tout angle inscrit dans un demi-cercle est droit (90°)", "L'angle central est la moitié de l'inscrit", "L'angle est de 60° toujours"], answer: 1, note: "Thalès (cercle) : si un angle inscrit a pour côté un diamètre, il est droit. Réciproque : angle droit → côté opposé = diamètre." },
    { q: "La somme des angles d'un triangle est :", choices: ["180° (π radians)", "90°", "360°", "270°"], answer: 0, note: "Propriété fondamentale de la géométrie euclidienne plane. La somme des angles intérieurs d'un triangle = 180°." },
    { q: "tan(45°) = tan(π/4) = :", choices: ["0", "1", "√3", "1/√3"], answer: 1, note: "tan(45°) = sin(45°)/cos(45°) = (√2/2)/(√2/2) = 1. Valeurs : tan(0°)=0, tan(30°)=1/√3, tan(45°)=1, tan(60°)=√3." },
    { q: "Le théorème d'Al-Kashi (loi des cosinus) dans un triangle ABC est :", choices: ["a = b + c", "a² = b² + c² - 2bc·cos(A)", "a² = b² + c² + 2bc·cos(A)", "a² = (b+c)²"], answer: 1, note: "Al-Kashi (généralisation de Pythagore) : a²=b²+c²-2bc·cos(A). Si A=90° : a²=b²+c² (Pythagore)." },
    { q: "La norme (longueur) d'un vecteur u⃗(a,b) est :", choices: ["|u⃗| = a + b", "|u⃗| = √(a² + b²)", "|u⃗| = a² + b²", "|u⃗| = |a| × |b|"], answer: 1, note: "|u⃗| = √(a²+b²). C'est la longueur du vecteur. Identique au module du complexe a+bi." },
    { q: "Le volume d'un cube de côté a est :", choices: ["V = a²", "V = a³", "V = 6a²", "V = (4/3)πa³"], answer: 1, note: "Volume cube = a³. Aire totale = 6a². Diagonale du cube = a√3. À distinguer de la sphère : V = (4/3)πr³." },
    { q: "L'homothétie de centre O et de rapport k : le segment OM'⃗ = :", choices: ["OM'⃗ = OM⃗ + k", "OM'⃗ = k·OM⃗", "OM'⃗ = OM⃗/k", "OM'⃗ = OM⃗"], answer: 1, note: "Homothétie : OM'⃗ = k·OM⃗. Si k=2 : distances doublées. Si k=-1 : symétrie centrale par rapport à O." },
    { q: "L'équation paramétrique d'une droite passant par A(x₀,y₀) de vecteur directeur d⃗(l,m) est :", choices: ["x=x₀+t, y=y₀+t", "x=x₀+lt, y=y₀+mt (t∈ℝ)", "x=x₀×t, y=y₀×t", "x=x₀/t, y=y₀/t"], answer: 1, note: "Représentation paramétrique : x=x₀+lt, y=y₀+mt. Éliminant t : équation cartésienne de la droite." },
  ],

  // ============================================================
  // LLA → DISSERTATION
  // ============================================================
  "Dissertation": [
    { q: "Une dissertation est :", choices: ["Un résumé de texte", "Un développement écrit structuré répondant à une problématique par une thèse argumentée et illustrée", "Une copie de textes étudiés", "Un exposé oral uniquement"], answer: 1, note: "Dissertation : exercice académique fondamental. Compétence centrale au NS4 — problématique + argumentation rigoureuse + exemples précis." },
    { q: "La problématique d'une dissertation est :", choices: ["Le titre du sujet", "La question centrale qui oriente l'ensemble du développement — reformulation dynamique du sujet", "La conclusion du devoir", "Le plan détaillé"], answer: 1, note: "Problématique : cœur de la dissertation. Elle doit être précise, pertinente, et orienter tout le développement." },
    { q: "La structure classique d'une dissertation comporte :", choices: ["Résumé + liste + conclusion", "Introduction + Développement (parties I, II, III avec sous-parties) + Conclusion", "Seulement introduction et conclusion", "Un texte libre sans structure"], answer: 1, note: "Structure en 3 temps : Introduction (accroche, contextualisation, problématique, plan), Développement (parties + exemples), Conclusion (bilan + ouverture)." },
    { q: "L'introduction d'une dissertation doit :", choices: ["Donner la réponse finale immédiatement", "Accrocher le lecteur, contextualiser, formuler la problématique et annoncer le plan", "Résumer uniquement l'œuvre étudiée", "Copier l'énoncé du sujet"], answer: 1, note: "Introduction en 4 temps : (1) accroche/attaque, (2) contextualisation, (3) problématique, (4) annonce du plan." },
    { q: "La conclusion d'une dissertation doit :", choices: ["Introduire de nouvelles idées non développées", "Synthétiser le développement, répondre à la problématique et proposer une ouverture", "Répéter mot pour mot l'introduction", "Citer uniquement des auteurs"], answer: 1, note: "Conclusion : (1) synthèse/bilan, (2) réponse claire à la problématique, (3) ouverture (élargissement vers une question connexe)." },
    { q: "Le plan dialectique (thèse-antithèse-synthèse) convient quand :", choices: ["Le sujet est une description pure", "Le sujet oppose deux points de vue (ex: 'La technique est-elle libératrice ou aliénante?')", "On doit raconter une histoire chronologique", "Le sujet est une définition simple"], answer: 1, note: "Plan dialectique : thèse (position A) → antithèse (position contraire B) → synthèse (dépassement nuancé C). Pour les sujets binaires." },
    { q: "La transition entre deux parties d'une dissertation sert à :", choices: ["Allonger le devoir", "Faire le bilan de la partie précédente et annoncer logiquement la suivante — assurer la cohérence", "Répéter ce qui vient d'être dit", "Introduire des exemples supplémentaires"], answer: 1, note: "Transition = conclusion partielle + articulation logique (cependant, c'est pourquoi, néanmoins...) + annonce de la partie suivante." },
    { q: "La paraphrase dans une dissertation est :", choices: ["Recommandée pour montrer la compréhension", "À éviter — reformuler sans analyser est insuffisant. Il faut interpréter, analyser, critiquer", "Obligatoire en introduction", "Nécessaire pour chaque citation"], answer: 1, note: "Paraphrase = reformulation sans analyse = défaut majeur noté. La dissertation exige une posture analytique et critique, pas la simple restitution." },
    { q: "La reformulation du sujet en problématique consiste à :", choices: ["Copier le sujet tel quel", "Identifier les concepts-clés, les enjeux et formuler une question que le développement va résoudre", "Donner immédiatement la réponse", "Définir tous les mots du sujet au dictionnaire"], answer: 1, note: "Reformulation : (1) mots-clés, (2) définition des concepts, (3) tension/paradoxe, (4) question centrale qui guide le développement." },
    { q: "La concession dans une argumentation consiste à :", choices: ["Refuser tout point de vue contraire", "Reconnaître une part de vérité dans l'argument adverse avant de nuancer ou réfuter — technique rhétorique efficace", "Répéter sa propre thèse", "Ignorer les contre-arguments"], answer: 1, note: "Concession : 'Certes, on peut admettre que... Cependant, il convient de nuancer car...' Montre l'honnêteté intellectuelle." },
    { q: "L'accroche (attaque) d'une introduction peut être :", choices: ["La définition du dictionnaire uniquement", "Une citation, un fait frappant, un paradoxe, une question rhétorique ou un constat d'actualité", "Un résumé du devoir", "La réponse à la problématique"], answer: 1, note: "Accroches efficaces : citation d'auteur pertinente, fait historique marquant, paradoxe apparent, statistique surprenante." },
    { q: "Un argument est solide quand :", choices: ["Il est très long", "Il est logiquement valide, pertinent par rapport à la thèse et illustré par un exemple précis et analysé", "Il utilise uniquement des citations célèbres", "Il est répété plusieurs fois"], answer: 1, note: "Bon argument : logique + pertinence + exemple (fait historique, œuvre, statistique) analysé. Structure : arg → explication → exemple → conclusion partielle." },
    { q: "Le registre de langue dans une dissertation académique doit être :", choices: ["Familier et conversationnel", "Soutenu et précis — vocabulaire riche, syntaxe correcte, connecteurs logiques, pas d'expressions populaires", "Uniquement technique", "Poétique et lyrique"], answer: 1, note: "Niveau soutenu : phrases complètes et correctes, vocabulaire précis, connecteurs logiques (ainsi, cependant, en revanche...). Éviter 'on voit que', 'je pense que'." },
    { q: "Le hors-sujet en dissertation est :", choices: ["Acceptable si bien rédigé", "Une faute grave — développer des idées non liées à la problématique posée = note très faible", "Toléré si les exemples sont bons", "Normal pour élargir la réflexion"], answer: 1, note: "Hors-sujet : erreur rédhibitoire. Tout le développement doit répondre à la problématique posée. Chaque argument doit être rattaché explicitement au sujet." },
    { q: "La citation dans une dissertation doit être :", choices: ["La plus longue possible", "Courte, attribuée précisément, intégrée naturellement et commentée/analysée", "Utilisée uniquement en introduction", "Traduite uniquement"], answer: 1, note: "Citation efficace : (1) intégrée naturellement, (2) attribuée (auteur, œuvre), (3) analysée (qu'est-ce qu'elle prouve ?). ≠ citation décorative." },
    { q: "En dissertation haïtienne (NS4), les exemples pertinents incluent :", choices: ["Uniquement des exemples européens", "Des références à la Révolution haïtienne, aux œuvres de Price-Mars, Roumain, Chauvet, aux données sur Haïti + universels", "Uniquement des données statistiques", "Uniquement des citations d'auteurs français"], answer: 1, note: "Dissertation NS4 : mobiliser exemples haïtiens (Révolution 1804, littérature haïtienne, réalité sociale) ET universels (auteurs, événements mondiaux)." },
    { q: "La structure thèse → exemple → explication dans un paragraphe s'appelle :", choices: ["La structure SWOT", "La méthode TEAR (Thèse, Exemple, Analyse, Récapitulatif) ou PEE (Point, Evidence, Explanation)", "La méthode dialectique", "La structure chronologique"], answer: 1, note: "Structure d'un bon paragraphe argumentatif : affirmation (thèse) → preuve (exemple précis) → analyse (explication) → lien avec la problématique." },
    { q: "L'objectivité dans une dissertation signifie :", choices: ["Ne jamais donner son avis", "Étayer ses affirmations par des preuves, nuancer ses propos et considérer les perspectives contraires", "Être entièrement neutre sans jamais défendre de thèse", "Citer uniquement des sources officielles"], answer: 1, note: "Objectivité ≠ absence de thèse. Défendre une position rigoureuse, honnête et nuancée, fondée sur des preuves — pas sur des opinions non étayées." },
    { q: "Un plan thématique (analytique) convient quand :", choices: ["Il faut s'opposer à une affirmation binaire", "Le sujet demande d'explorer plusieurs aspects d'une même question sans opposition frontale (description, analyse)", "On fait une narration chronologique pure", "Le sujet demande une définition simple"], answer: 1, note: "Plan thématique : examine plusieurs dimensions (économique, social, culturel, politique) du phénomène étudié. Non dialectique." },
    { q: "La dissertation de philosophie au NS4 exige notamment :", choices: ["Uniquement la mémorisation de citations", "La maîtrise des concepts philosophiques, une pensée critique personnelle, des exemples et une argumentation rigoureuse", "La copie d'analyses de manuels", "Seulement un résumé des auteurs étudiés"], answer: 1, note: "Dissertation philo NS4 : mobilisation des concepts (conscience, liberté, justice, travail...) + auteurs (Kant, Sartre, Roumain, Price-Mars) + argumentation rigoureuse." },
  ],

  // ============================================================
  // LLA → ÉDUCATION PHYSIQUE ET SPORTIVE
  // ============================================================
  "Éducation Physique et Sportive": [
    { q: "L'EPS au secondaire haïtien (programme MENFP 2024) vise principalement :", choices: ["Former des athlètes professionnels uniquement", "Développer les capacités physiques, la santé, les méthodes d'apprentissage, la relation à l'autre et la citoyenneté", "Remplacer les cours académiques", "Uniquement faire du sport de compétition"], answer: 1, note: "Programme EPS MENFP : 4 compétences générales — motricité, relation à l'autre, santé/sécurité, patrimoine culturel sportif. 5 champs d'apprentissage." },
    { q: "Les bénéfices de l'activité physique régulière incluent :", choices: ["Uniquement la perte de poids", "Amélioration cardiovasculaire, ossification, humeur (endorphines), concentration, sommeil et immunité", "Uniquement le développement musculaire", "Uniquement des bénéfices physiques, pas mentaux"], answer: 1, note: "OMS recommande : 60 min/jour d'activité modérée à intense pour les adolescents. Bénéfices multiples : cœur, os, muscles, bien-être mental." },
    { q: "La fréquence cardiaque maximale théorique (FCmax) est calculée par :", choices: ["200 - âge", "220 - âge (formule de Karvonen)", "180 - âge", "250 - âge"], answer: 1, note: "FCmax théorique = 220 - âge. Pour un adolescent de 17 ans : FCmax ≈ 203 bpm. Zone d'entraînement aérobie : 60-85% de FCmax." },
    { q: "L'échauffement avant une activité sportive est important car :", choices: ["C'est une obligation scolaire uniquement", "Il prépare progressivement les muscles, articulations et système cardiovasculaire, réduisant le risque de blessures", "Il remplace l'entraînement principal", "Il n'est nécessaire que pour les compétitions"], answer: 1, note: "Échauffement : élève la température musculaire, lubrifie les articulations, active le SNC, augmente progressivement la FC → prévient déchirures et entorses." },
    { q: "Le fair-play en sport signifie :", choices: ["Gagner à tout prix", "Respecter les règles, l'adversaire et l'arbitre — jouer loyalement et accepter honnêtement le résultat", "Tricher intelligemment sans se faire voir", "Éviter toute compétition"], answer: 1, note: "Fair-play (jeu équitable) : valeur fondamentale du sport et de l'olympisme. Respect des règles, de l'adversaire, de l'arbitre, comportement éthique." },
    { q: "La distance officielle d'un marathon est :", choices: ["21,1 km", "42,195 km", "40 km", "50 km"], answer: 1, note: "Marathon : 42,195 km. Origine : légende de Phidippidès (490 av.J.-C.). Distance standardisée depuis les JO de Londres 1908." },
    { q: "L'IMC (Indice de Masse Corporelle) se calcule par :", choices: ["Poids (kg) + Taille (m)", "Poids (kg) / Taille² (m²)", "Poids (kg) × Taille (m)", "Taille (m) / Poids (kg)"], answer: 1, note: "IMC = Poids/Taille². Normal : 18,5-24,9. Sous-poids : <18,5. Surpoids : 25-29,9. Obésité : ≥30. Indicateur simple, imparfait (ne mesure pas la masse grasse)." },
    { q: "Le sport est un outil de développement social car :", choices: ["Il crée uniquement de la compétition", "Il favorise l'inclusion sociale, la cohésion, la discipline, la réduction des comportements violents et la santé publique", "Il exclut les personnes moins performantes", "Il coûte trop cher pour être accessible"], answer: 1, note: "Sport et développement : ONU reconnaît le sport comme outil de paix et développement (Résolution 58/5, 2003). Inclusion, cohésion, santé publique, discipline." },
    { q: "Les 5 champs d'apprentissage de l'EPS (programme MENFP 2024) comprennent :", choices: ["Uniquement les sports collectifs", "Activités athlétiques/performance, adaptation/incertitude, opposition/combat, expression/artistique, entretien/bien-être", "Uniquement la course et le saut", "Uniquement les sports d'équipe"], answer: 1, note: "Programme EPS MENFP (2024) : 5 champs — (1) performer/vitesse/endurance, (2) s'adapter/milieu incertain, (3) s'opposer/combat, (4) s'exprimer/créer, (5) bien-être/entretien." },
    { q: "La récupération après l'effort est importante car :", choices: ["Elle ralentit la progression", "Elle permet aux muscles de se reconstruire, à l'organisme de s'adapter et prévient le surentraînement", "Elle doit être la plus courte possible", "Elle n'est nécessaire que pour les professionnels"], answer: 1, note: "Récupération : réparation des micro-lésions musculaires, resynthèse du glycogène, adaptation neuromusculaire. Sans récupération adéquate → surentraînement → blessures." },
    { q: "Le principe de progressivité en entraînement sportif signifie :", choices: ["Commencer très fort et réduire progressivement", "Augmenter graduellement la charge de travail (intensité, volume) pour respecter les adaptations physiologiques", "Faire toujours le même entraînement", "Alterner entraînement intense et repos total"], answer: 1, note: "Progressivité : principe fondamental. L'organisme s'adapte progressivement. Augmenter trop vite → blessures. Trop peu → stagnation (plateau)." },
    { q: "La déshydratation durant l'effort physique peut causer :", choices: ["Une amélioration des performances", "Baisse des performances, crampes, vertiges, coup de chaleur et complications graves dans les cas sévères", "Une augmentation de la force musculaire", "Aucun effet significatif"], answer: 1, note: "Déshydratation : -2% du poids en eau → -10% de performance. Boire régulièrement avant/pendant/après l'effort est essentiel surtout en climat tropical (Haïti)." },
    { q: "La posture corporelle correcte pendant l'effort physique vise à :", choices: ["Paraître esthétique uniquement", "Optimiser l'efficacité du mouvement, prévenir les blessures et réduire la fatigue inutile", "Impressionner les spectateurs", "Ralentir l'athlète"], answer: 1, note: "Posture correcte : alignement corps-nuque-bassin, gainage actif, respiration contrôlée → efficacité maximale, prévention des lombalgies et tendinites." },
    { q: "Haïti a-t-elle participé aux Jeux Olympiques ?", choices: ["Non, jamais", "Oui — première participation en 1900 (Paris). Haïti est l'un des premiers pays afro-caribéens aux JO", "Oui, uniquement depuis 2000", "Oui, uniquement en sports aquatiques"], answer: 1, note: "Haïti aux JO : première participation en 1900 (Paris). Comité Olympique Haïtien (COH) fondé en 1924. 1928 : Sylvio Cator, médaille d'argent au saut en longueur." },
    { q: "L'endurance cardiovasculaire est améliorée par :", choices: ["Les exercices de force courte durée uniquement", "Les activités aérobies continues (course, natation, vélo) à intensité modérée sur durée prolongée", "Les sprints uniquement", "Le stretching statique"], answer: 1, note: "Endurance aérobie : entraînement à 60-75% FCmax, 20-60 min, 3-5 fois/semaine. Améliore VO₂max, efficacité cardiaque, capillarisation musculaire." },
  ],

  // ============================================================
  // LLA → LITTÉRATURE FRANÇAISE
  // ============================================================
  "Littérature Française": [
    { q: "Victor Hugo (1802-1885) est le chef de file du :", choices: ["Classicisme", "Romantisme français — la Préface de Cromwell (1827) est son manifeste théorique", "Naturalisme", "Surréalisme"], answer: 1, note: "Hugo : chef du Romantisme français. Préface de Cromwell (1827) : liberté créatrice, mélange des genres (tragique/comique), rejet des unités classiques." },
    { q: "'Les Misérables' (1862) de Victor Hugo raconte :", choices: ["Les aventures d'un pirate", "Le parcours de Jean Valjean, ancien forçat cherchant la rédemption dans une France du 19e siècle inégalitaire", "La Révolution française", "La vie à la cour de Louis XIV"], answer: 1, note: "Les Misérables : roman social et humaniste. Jean Valjean, Cosette, Fantine, Gavroche, Javert — lutte pour la dignité, dénonciation de la pauvreté et de l'injustice." },
    { q: "Le thème central des 'Misérables' est :", choices: ["La guerre napoléonienne", "La justice sociale, la rédemption et la lutte contre les inégalités dans la France du 19e siècle", "L'amour courtois médiéval", "La colonisation africaine"], answer: 1, note: "Les Misérables : Hugo dénonce la misère, l'injustice sociale, l'hypocrisie légale. Plaide pour la dignité humaine universelle." },
    { q: "Gavroche dans 'Les Misérables' représente :", choices: ["L'enfant bourgeois parisien", "Le gamin du peuple de Paris — espiègle, généreux, rebelle, mort héroïquement sur les barricades de 1832", "Un noble déguisé", "Un policier infiltré"], answer: 1, note: "Gavroche : fils abandonné des Thénardier, vit dans un éléphant de bronze. Figure mythique du gamin de Paris. Mort sur les barricades de la rue Saint-Denis (1832)." },
    { q: "Molière (1622-1673) est le maître de :", choices: ["La tragédie classique", "La comédie française — satire des vices et hypocrisies humaines ('castigat ridendo mores')", "L'épopée héroïque", "La poésie lyrique"], answer: 1, note: "Molière (Jean-Baptiste Poquelin) : maître de la comédie de mœurs. 'Castigat ridendo mores' = châtier les mœurs en riant. Protégé de Louis XIV." },
    { q: "'Le Malade imaginaire' (1673) de Molière dénonce :", choices: ["La pauvreté des médecins", "La médecine du 17e s. et l'hypocondrie d'Argan exploitée par des médecins charlatans et cupides", "La politique royale", "La religion directement"], answer: 1, note: "Le Malade imaginaire : Argan hypocondriaque manipulé par M. Diafoirus (médecin pédant) et Béline (femme intéressée). Satire de la médecine galénique." },
    { q: "'Tartuffe' (1664) de Molière dénonce :", choices: ["L'avarice des bourgeois", "L'hypocrisie religieuse — Tartuffe, faux dévot, abuse de la confiance d'Orgon aveuglé par la piété", "La noblesse française", "L'éducation des enfants"], answer: 1, note: "Tartuffe : feint la piété pour s'emparer des biens d'Orgon et séduire Elmire. Pièce controversée — Louis XIV l'interdit en 1664 puis en autorise la reprise en 1669." },
    { q: "Albert Camus (1913-1960) est l'auteur de :", choices: ["Les Misérables", "L'Étranger (1942), La Peste (1947), Le Mythe de Sisyphe (1942) — Prix Nobel 1957", "Germinal", "Tartuffe"], answer: 1, note: "Camus : auteur franco-algérien. Philosophie de l'absurde et de la révolte. Né à Mondovi (Algérie), mort dans un accident de voiture le 4 janvier 1960." },
    { q: "L'incipit de 'L'Étranger' (Camus) est :", choices: ["'Il était une fois un homme...'", "'Aujourd'hui, maman est morte. Ou peut-être hier, je ne sais pas.'", "'Longtemps je me suis couché de bonne heure.'", "'Je suis né le jour où mes parents ont voulu me tuer.'"], answer: 1, note: "Incipit d'anthologie : ton neutre et détaché révèle immédiatement l'étrangeté de Meursault. Passé composé 'style blanc' (Albert Camus, Roland Barthes)." },
    { q: "La philosophie de l'absurde selon Camus est :", choices: ["La vie a un sens évident donné par Dieu", "Un conflit irréductible entre le désir humain de sens et le silence irrationnel du monde", "La mort donne un sens à la vie", "La religion résout le problème du sens"], answer: 1, note: "Absurde (Camus) : confrontation entre désir de clarté (humain) et silence du monde (réel). Ni suicide, ni espoir religieux → la révolte est la réponse." },
    { q: "Émile Zola (1840-1902) est le chef de file du :", choices: ["Romantisme", "Naturalisme — 'Le Roman expérimental' (1880) : appliquer la méthode scientifique au roman", "Symbolisme", "Classicisme"], answer: 1, note: "Zola : Naturalisme — observation, documentation, expérimentation littéraire. Cycle des Rougon-Macquart (20 romans) : hérédité + milieu social = destin." },
    { q: "'Germinal' (1885) de Zola se déroule dans :", choices: ["Paris bourgeois", "Les mines de charbon du Nord de la France — misère, exploitation et grande grève ouvrière", "La campagne provençale", "L'Algérie coloniale"], answer: 1, note: "Germinal : mines de Montsou. Famille Maheu, Étienne Lantier, grève et répression. Zola enquête sur le terrain à Anzin (1884) pour documenter avec précision." },
    { q: "Jean de La Fontaine (1621-1695) est connu pour :", choices: ["Ses tragédies", "Ses Fables (1668-1694) — 12 livres, ~240 fables en vers, inspirées d'Ésope et Phèdre", "Ses comédies de mœurs", "Ses poèmes épiques"], answer: 1, note: "La Fontaine : maître de la fable en vers, genre didactique et moral. Double lecture : récit divertissant + morale sociale. Classicisme du XVIIe siècle." },
    { q: "La morale 'La Raison du plus fort est toujours la meilleure' est la morale de :", choices: ["La Cigale et la Fourmi", "Le Loup et l'Agneau (Livre I, 10)", "Le Corbeau et le Renard", "Le Lion et le Rat"], answer: 1, note: "Le Loup et l'Agneau : le loup trouve toujours un prétexte pour dévorer l'agneau innocent → dénonciation de l'abus de pouvoir des forts sur les faibles." },
    { q: "Voltaire (1694-1778) est l'auteur de :", choices: ["Les Misérables", "Candide ou l'Optimisme (1759) — conte philosophique des Lumières", "Germinal", "Le Malade imaginaire"], answer: 1, note: "Voltaire (François-Marie Arouet) : figure emblématique des Lumières. 'Écrasez l'infâme !' (contre le fanatisme religieux). Combats pour la tolérance et la justice." },
    { q: "La conclusion de 'Candide' ('il faut cultiver notre jardin') signifie :", choices: ["Il faut jardiner concrètement", "Il faut agir concrètement dans son monde proche plutôt que de spéculer abstraitement — pragmatisme des Lumières", "Il faut fuir le monde dans la nature", "L'optimisme naïf est la seule solution"], answer: 1, note: "'Cultiver son jardin' : renoncer aux spéculations métaphysiques stériles et agir modestement mais efficacement. Message pragmatique et humaniste." },
    { q: "Jean Racine (1639-1699) est le maître de :", choices: ["La comédie", "La tragédie classique (Andromaque, Phèdre, Bérénice) — passions humaines destructrices dans les règles classiques", "L'épopée", "La fable"], answer: 1, note: "Racine : Phèdre (1677) = chef-d'œuvre. Règle des 3 unités, alexandrins, passions irrationnelles comme destin. Rival de Corneille, protégé de Louis XIV." },
    { q: "Les trois unités du théâtre classique français (17e s.) sont :", choices: ["Lieu, temps et action", "Style, longueur et décor", "Héros, conflit et dénouement", "Langue, époque et personnages"], answer: 0, note: "Règle des 3 unités (codifiant Aristote) : (1) unité d'action (une intrigue principale), (2) de temps (24h max), (3) de lieu (un seul endroit)." },
    { q: "Charles Baudelaire (1821-1867) est l'auteur de :", choices: ["Les Contemplations", "Les Fleurs du Mal (1857) — recueil fondateur de la modernité poétique", "Alcools", "Les Misérables"], answer: 1, note: "'Les Fleurs du Mal' (1857) : spleen, idéal, corruption, beauté du mal. Condamné à sa parution. Fondateur du Symbolisme, père de la poésie moderne." },
    { q: "Aimé Césaire (Martinique, 1913-2008) a fondé :", choices: ["L'Indigénisme haïtien", "La Négritude — avec Senghor et Damas — revalorisation des cultures africaines et de l'identité noire", "Le Symbolisme français", "Le Surréalisme"], answer: 1, note: "Négritude (années 1930-40, Paris) : Césaire, Senghor, Damas. 'Cahier d'un retour au pays natal' (1939) = manifeste fondateur. Influence majeure sur Price-Mars et la littérature haïtienne." },
    { q: "Le mouvement des Lumières (18e s.) prône :", choices: ["La foi aveugle et la tradition", "La raison, la tolérance, la liberté et la lutte contre l'obscurantisme et le despotisme", "Le retour au Moyen Âge", "La suprématie de l'Église sur l'État"], answer: 1, note: "Lumières (Voltaire, Rousseau, Diderot, Montesquieu) : Encyclopédie (1751-1772). Raison vs superstition. Influence directe sur la Révolution française et haïtienne de 1804." },
    { q: "Jean-Paul Sartre (1905-1980) défend :", choices: ["L'essence précède l'existence", "L'existentialisme : 'l'existence précède l'essence' — l'homme se définit par ses choix libres", "Le déterminisme absolu", "Le mysticisme religieux"], answer: 1, note: "Sartre : L'Être et le Néant (1943), L'Existentialisme est un humanisme (1945). 'Condamné à être libre.' Refus du Prix Nobel (1964). Figure intellectuelle du 20e siècle." },
    { q: "André Breton (1896-1966) a fondé :", choices: ["Le Symbolisme", "Le Surréalisme (Manifeste du Surréalisme, 1924) — libérer l'inconscient et le rêve dans la création", "L'Existentialisme", "Le Réalisme socialiste"], answer: 1, note: "Surréalisme : automatisme psychique, rêve, inconscient. Influence Dali, Magritte, Ernst. Césaire intègre le surréalisme dans la négritude haïtienne." },
    { q: "La Préface de Cromwell (1827) de Victor Hugo est :", choices: ["Un roman historique", "Le manifeste théorique du Romantisme français — liberté créatrice, mélange des genres, rejet des unités classiques", "Une biographie de Cromwell", "Un traité de théologie politique"], answer: 1, note: "Préface de Cromwell (1827) : texte fondateur du Romantisme. Hugo réclame la liberté de l'art, le mélange du sublime et du grotesque, contre les règles classiques." },
  ],

};
